// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file api/allocations.proto (package printrfi.api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Platform } from "../chains/chains_pb.js";

/**
 * @generated from message printrfi.api.GetAllocationsRequest
 */
export class GetAllocationsRequest extends Message<GetAllocationsRequest> {
  /**
   * @generated from field: string wallet = 1;
   */
  wallet = "";

  /**
   * @generated from field: string campaign = 2;
   */
  campaign = "";

  constructor(data?: PartialMessage<GetAllocationsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.GetAllocationsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "wallet", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "campaign", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GetAllocationsRequest {
    return new GetAllocationsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllocationsRequest {
    return new GetAllocationsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GetAllocationsRequest {
    return new GetAllocationsRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a: GetAllocationsRequest | PlainMessage<GetAllocationsRequest> | undefined,
    b: GetAllocationsRequest | PlainMessage<GetAllocationsRequest> | undefined,
  ): boolean {
    return proto3.util.equals(GetAllocationsRequest, a, b);
  }
}

/**
 * @generated from message printrfi.api.AllocationAction
 */
export class AllocationAction extends Message<AllocationAction> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string label = 2;
   */
  label = "";

  /**
   * @generated from field: int32 points = 3;
   */
  points = 0;

  constructor(data?: PartialMessage<AllocationAction>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.AllocationAction";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "points", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AllocationAction {
    return new AllocationAction().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AllocationAction {
    return new AllocationAction().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AllocationAction {
    return new AllocationAction().fromJsonString(jsonString, options);
  }

  static equals(
    a: AllocationAction | PlainMessage<AllocationAction> | undefined,
    b: AllocationAction | PlainMessage<AllocationAction> | undefined,
  ): boolean {
    return proto3.util.equals(AllocationAction, a, b);
  }
}

/**
 * @generated from message printrfi.api.GetAllocationsResponse
 */
export class GetAllocationsResponse extends Message<GetAllocationsResponse> {
  /**
   * empty when wallet has no allocations
   *
   * @generated from field: optional string wallet = 1;
   */
  wallet?: string;

  /**
   * @generated from field: printrfi.chains.Platform platform = 2;
   */
  platform = Platform.UNKNOWN;

  /**
   * @generated from field: repeated printrfi.api.AllocationAction actions = 3;
   */
  actions: AllocationAction[] = [];

  /**
   * @generated from field: int32 total_points = 4;
   */
  totalPoints = 0;

  constructor(data?: PartialMessage<GetAllocationsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.GetAllocationsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "wallet", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "platform", kind: "enum", T: proto3.getEnumType(Platform) },
    { no: 3, name: "actions", kind: "message", T: AllocationAction, repeated: true },
    { no: 4, name: "total_points", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GetAllocationsResponse {
    return new GetAllocationsResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): GetAllocationsResponse {
    return new GetAllocationsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GetAllocationsResponse {
    return new GetAllocationsResponse().fromJsonString(jsonString, options);
  }

  static equals(
    a: GetAllocationsResponse | PlainMessage<GetAllocationsResponse> | undefined,
    b: GetAllocationsResponse | PlainMessage<GetAllocationsResponse> | undefined,
  ): boolean {
    return proto3.util.equals(GetAllocationsResponse, a, b);
  }
}
