// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file api/api.proto (package printrfi.api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AttachWalletRequest, AttachWalletResponse, ChainsRequest, ChainsResponse, CreateRequest, CreateResponse, DeleteCommentRequest, DeleteCommentResponse, DeployRequest, DeployResponse, DetachWalletRequest, DetachWalletResponse, FollowTelecoinsRequest, FollowTelecoinsResponse, GetCommentsRequest, GetCommentsResponse, GetFollowedTelecoinsRequest, GetFollowedTelecoinsResponse, GetProfileByWalletRequest, GetProfileByWalletResponse, GetProfileRequest, GetProfileResponse, GetProfilesByWalletsRequest, GetProfilesByWalletsResponse, GetTokensByAddressRequest, GetTokensByAddressResponse, GetTokensRequest, GetTokensResponse, IssueProfileRequest, IssueProfileResponse, LikeCommentRequest, LikeCommentResponse, LinkTwitterRequest, LinkTwitterResponse, ListTokensRequest, ListTokensResponse, ListXchainMsgsRequest, ListXchainMsgsResponse, PostCommentRequest, PostCommentResponse, ProtocolFeesRequest, ProtocolFeesResponse, SellRequest, SellResponse, SpendRequest, SpendResponse, TransferRequest, TransferResponse, UnfollowTelecoinsRequest, UnfollowTelecoinsResponse, UnlinkTwitterRequest, UnlinkTwitterResponse, UpdateProfileRequest, UpdateProfileResponse, UploadProfileImageRequest, UploadProfileImageResponse } from "./api_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { QuoteSpendOnTelecoinRequest, QuoteSpendOnTelecoinResponse } from "./quote_spend_on_telecoin_pb.js";
import { SpendOnTelecoinRequest, SpendOnTelecoinResponse } from "./spend_on_telecoin_pb.js";
import { CreateStakePositionRequest, CreateStakePositionResponse } from "./create_stake_position_pb.js";
import { ClaimStakingRewardsRequest, ClaimStakingRewardsResponse } from "./claim_staking_rewards_pb.js";
import { ListStakePositionsRequest, ListStakePositionsResponse, ListStakePositionsWithRewardsResponse } from "./list_stake_positions_pb.js";
import { GetAllocationsRequest, GetAllocationsResponse } from "./allocations_pb.js";
import { GetTelecoinDeploymentBuybackAndBurnDetailRequest, GetTelecoinDeploymentBuybackAndBurnDetailResponse } from "./get_buyback_and_burn_detail_pb.js";

/**
 * @generated from service printrfi.api.Backend
 */
export const Backend = {
  typeName: "printrfi.api.Backend",
  methods: {
    /**
     * @generated from rpc printrfi.api.Backend.Create
     */
    create: {
      name: "Create",
      I: CreateRequest,
      O: CreateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * builds calldata but doesn't add it to the db (for fee updates)
     * nb: maybe rename to BuildCreateCalldata or RouteDeployTx?
     *
     * @generated from rpc printrfi.api.Backend.Deploy
     */
    deploy: {
      name: "Deploy",
      I: DeployRequest,
      O: DeployResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.GetTokens
     */
    getTokens: {
      name: "GetTokens",
      I: GetTokensRequest,
      O: GetTokensResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.Spend
     * @deprecated
     */
    spend: {
      name: "Spend",
      I: SpendRequest,
      O: SpendResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.Sell
     */
    sell: {
      name: "Sell",
      I: SellRequest,
      O: SellResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Query accumulated protocol/liquidity fees across chains and return
     * distribution breakdowns and optional collection payloads per chain.
     *
     * @generated from rpc printrfi.api.Backend.ProtocolFees
     */
    protocolFees: {
      name: "ProtocolFees",
      I: ProtocolFeesRequest,
      O: ProtocolFeesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.Transfer
     */
    transfer: {
      name: "Transfer",
      I: TransferRequest,
      O: TransferResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.ListTokens
     */
    listTokens: {
      name: "ListTokens",
      I: ListTokensRequest,
      O: ListTokensResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.ListXchainMsgs
     */
    listXchainMsgs: {
      name: "ListXchainMsgs",
      I: ListXchainMsgsRequest,
      O: ListXchainMsgsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.GetTokensByAddress
     */
    getTokensByAddress: {
      name: "GetTokensByAddress",
      I: GetTokensByAddressRequest,
      O: GetTokensByAddressResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.FollowTelecoins
     */
    followTelecoins: {
      name: "FollowTelecoins",
      I: FollowTelecoinsRequest,
      O: FollowTelecoinsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.UnfollowTelecoins
     */
    unfollowTelecoins: {
      name: "UnfollowTelecoins",
      I: UnfollowTelecoinsRequest,
      O: UnfollowTelecoinsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.GetFollowedTelecoins
     */
    getFollowedTelecoins: {
      name: "GetFollowedTelecoins",
      I: GetFollowedTelecoinsRequest,
      O: GetFollowedTelecoinsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.Chains
     */
    chains: {
      name: "Chains",
      I: ChainsRequest,
      O: ChainsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.GetComments
     */
    getComments: {
      name: "GetComments",
      I: GetCommentsRequest,
      O: GetCommentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.PostComment
     */
    postComment: {
      name: "PostComment",
      I: PostCommentRequest,
      O: PostCommentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.DeleteComment
     */
    deleteComment: {
      name: "DeleteComment",
      I: DeleteCommentRequest,
      O: DeleteCommentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.LikeComment
     */
    likeComment: {
      name: "LikeComment",
      I: LikeCommentRequest,
      O: LikeCommentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.IssueProfile
     */
    issueProfile: {
      name: "IssueProfile",
      I: IssueProfileRequest,
      O: IssueProfileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.GetProfile
     */
    getProfile: {
      name: "GetProfile",
      I: GetProfileRequest,
      O: GetProfileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.UpdateProfile
     */
    updateProfile: {
      name: "UpdateProfile",
      I: UpdateProfileRequest,
      O: UpdateProfileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.UploadProfileImage
     */
    uploadProfileImage: {
      name: "UploadProfileImage",
      I: UploadProfileImageRequest,
      O: UploadProfileImageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.GetProfileByWallet
     */
    getProfileByWallet: {
      name: "GetProfileByWallet",
      I: GetProfileByWalletRequest,
      O: GetProfileByWalletResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.GetProfilesByWallets
     */
    getProfilesByWallets: {
      name: "GetProfilesByWallets",
      I: GetProfilesByWalletsRequest,
      O: GetProfilesByWalletsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.AttachWallet
     */
    attachWallet: {
      name: "AttachWallet",
      I: AttachWalletRequest,
      O: AttachWalletResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.DetachWallet
     */
    detachWallet: {
      name: "DetachWallet",
      I: DetachWalletRequest,
      O: DetachWalletResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.LinkTwitter
     */
    linkTwitter: {
      name: "LinkTwitter",
      I: LinkTwitterRequest,
      O: LinkTwitterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.UnlinkTwitter
     */
    unlinkTwitter: {
      name: "UnlinkTwitter",
      I: UnlinkTwitterRequest,
      O: UnlinkTwitterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.QuoteSpendOnTelecoin
     */
    quoteSpendOnTelecoin: {
      name: "QuoteSpendOnTelecoin",
      I: QuoteSpendOnTelecoinRequest,
      O: QuoteSpendOnTelecoinResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.SpendOnTelecoin
     */
    spendOnTelecoin: {
      name: "SpendOnTelecoin",
      I: SpendOnTelecoinRequest,
      O: SpendOnTelecoinResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.CreateStakePosition
     */
    createStakePosition: {
      name: "CreateStakePosition",
      I: CreateStakePositionRequest,
      O: CreateStakePositionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.ClaimStakingRewards
     */
    claimStakingRewards: {
      name: "ClaimStakingRewards",
      I: ClaimStakingRewardsRequest,
      O: ClaimStakingRewardsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.ListStakePositions
     */
    listStakePositions: {
      name: "ListStakePositions",
      I: ListStakePositionsRequest,
      O: ListStakePositionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.ListStakePositionsWithRewards
     */
    listStakePositionsWithRewards: {
      name: "ListStakePositionsWithRewards",
      I: ListStakePositionsRequest,
      O: ListStakePositionsWithRewardsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.GetAllocations
     */
    getAllocations: {
      name: "GetAllocations",
      I: GetAllocationsRequest,
      O: GetAllocationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.api.Backend.GetTelecoinDeploymentBuybackAndBurnDetail
     */
    getTelecoinDeploymentBuybackAndBurnDetail: {
      name: "GetTelecoinDeploymentBuybackAndBurnDetail",
      I: GetTelecoinDeploymentBuybackAndBurnDetailRequest,
      O: GetTelecoinDeploymentBuybackAndBurnDetailResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

