// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file api/claim_staking_rewards.proto (package printrfi.api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Account } from "../caip/account_pb.js";
import { TxPayload } from "./payload_pb.js";

/**
 * @generated from message printrfi.api.ClaimStakingRewardsRequest
 */
export class ClaimStakingRewardsRequest extends Message<ClaimStakingRewardsRequest> {
  /**
   * The CAIP-10 address of the stake position to claim rewards from.
   *
   * @generated from field: printrfi.caip.Account position = 1;
   */
  position?: Account;

  /**
   * The CAIP-10 address of the payer who signs and pays for the transaction.
   *
   * @generated from field: printrfi.caip.Account payer = 2;
   */
  payer?: Account;

  /**
   * The transaction ID that created this stake position.
   *
   * @generated from field: string creation_tx = 3;
   */
  creationTx = "";

  constructor(data?: PartialMessage<ClaimStakingRewardsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.ClaimStakingRewardsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "position", kind: "message", T: Account },
    { no: 2, name: "payer", kind: "message", T: Account },
    { no: 3, name: "creation_tx", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): ClaimStakingRewardsRequest {
    return new ClaimStakingRewardsRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): ClaimStakingRewardsRequest {
    return new ClaimStakingRewardsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): ClaimStakingRewardsRequest {
    return new ClaimStakingRewardsRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a: ClaimStakingRewardsRequest | PlainMessage<ClaimStakingRewardsRequest> | undefined,
    b: ClaimStakingRewardsRequest | PlainMessage<ClaimStakingRewardsRequest> | undefined,
  ): boolean {
    return proto3.util.equals(ClaimStakingRewardsRequest, a, b);
  }
}

/**
 * @generated from message printrfi.api.ClaimStakingRewardsResponse
 */
export class ClaimStakingRewardsResponse extends Message<ClaimStakingRewardsResponse> {
  /**
   * @generated from field: printrfi.api.TxPayload tx_payload = 1;
   */
  txPayload?: TxPayload;

  constructor(data?: PartialMessage<ClaimStakingRewardsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.ClaimStakingRewardsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tx_payload", kind: "message", T: TxPayload },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): ClaimStakingRewardsResponse {
    return new ClaimStakingRewardsResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): ClaimStakingRewardsResponse {
    return new ClaimStakingRewardsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): ClaimStakingRewardsResponse {
    return new ClaimStakingRewardsResponse().fromJsonString(jsonString, options);
  }

  static equals(
    a: ClaimStakingRewardsResponse | PlainMessage<ClaimStakingRewardsResponse> | undefined,
    b: ClaimStakingRewardsResponse | PlainMessage<ClaimStakingRewardsResponse> | undefined,
  ): boolean {
    return proto3.util.equals(ClaimStakingRewardsResponse, a, b);
  }
}
