// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file api/create_stake_position.proto (package printrfi.api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Account } from "../caip/account_pb.js";
import { AssetAmountV1 } from "./misc_pb.js";
import { TxPayload } from "./payload_pb.js";

/**
 * @generated from enum printrfi.api.StakingLockPeriod
 */
export enum StakingLockPeriod {
  /**
   * @generated from enum value: STAKING_LOCK_PERIOD_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STAKING_LOCK_PERIOD_SEVEN_DAYS = 1;
   */
  SEVEN_DAYS = 1,

  /**
   * @generated from enum value: STAKING_LOCK_PERIOD_FOURTEEN_DAYS = 2;
   */
  FOURTEEN_DAYS = 2,

  /**
   * @generated from enum value: STAKING_LOCK_PERIOD_THIRTY_DAYS = 3;
   */
  THIRTY_DAYS = 3,

  /**
   * @generated from enum value: STAKING_LOCK_PERIOD_SIXTY_DAYS = 4;
   */
  SIXTY_DAYS = 4,

  /**
   * @generated from enum value: STAKING_LOCK_PERIOD_NINETY_DAYS = 5;
   */
  NINETY_DAYS = 5,

  /**
   * @generated from enum value: STAKING_LOCK_PERIOD_ONE_HUNDRED_EIGHTY_DAYS = 6;
   */
  ONE_HUNDRED_EIGHTY_DAYS = 6,

  /**
   * @generated from enum value: STAKING_LOCK_PERIOD_TEN_SECONDS = 7;
   */
  TEN_SECONDS = 7,
}
// Retrieve enum metadata with: proto3.getEnumType(StakingLockPeriod)
proto3.util.setEnumType(StakingLockPeriod, "printrfi.api.StakingLockPeriod", [
  { no: 0, name: "STAKING_LOCK_PERIOD_UNSPECIFIED" },
  { no: 1, name: "STAKING_LOCK_PERIOD_SEVEN_DAYS" },
  { no: 2, name: "STAKING_LOCK_PERIOD_FOURTEEN_DAYS" },
  { no: 3, name: "STAKING_LOCK_PERIOD_THIRTY_DAYS" },
  { no: 4, name: "STAKING_LOCK_PERIOD_SIXTY_DAYS" },
  { no: 5, name: "STAKING_LOCK_PERIOD_NINETY_DAYS" },
  { no: 6, name: "STAKING_LOCK_PERIOD_ONE_HUNDRED_EIGHTY_DAYS" },
  { no: 7, name: "STAKING_LOCK_PERIOD_TEN_SECONDS" },
]);

/**
 * @generated from message printrfi.api.CreateStakePositionRequest
 */
export class CreateStakePositionRequest extends Message<CreateStakePositionRequest> {
  /**
   * @generated from field: string telecoin_id = 1;
   */
  telecoinId = "";

  /**
   * @generated from field: printrfi.caip.Account payer = 2;
   */
  payer?: Account;

  /**
   * @generated from field: printrfi.api.AssetAmountV1 to_stake = 3;
   */
  toStake?: AssetAmountV1;

  /**
   * @generated from field: printrfi.api.StakingLockPeriod lock_period = 4;
   */
  lockPeriod = StakingLockPeriod.UNSPECIFIED;

  constructor(data?: PartialMessage<CreateStakePositionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.CreateStakePositionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "telecoin_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "payer", kind: "message", T: Account },
    { no: 3, name: "to_stake", kind: "message", T: AssetAmountV1 },
    { no: 4, name: "lock_period", kind: "enum", T: proto3.getEnumType(StakingLockPeriod) },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): CreateStakePositionRequest {
    return new CreateStakePositionRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): CreateStakePositionRequest {
    return new CreateStakePositionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): CreateStakePositionRequest {
    return new CreateStakePositionRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a: CreateStakePositionRequest | PlainMessage<CreateStakePositionRequest> | undefined,
    b: CreateStakePositionRequest | PlainMessage<CreateStakePositionRequest> | undefined,
  ): boolean {
    return proto3.util.equals(CreateStakePositionRequest, a, b);
  }
}

/**
 * @generated from message printrfi.api.CreateStakePositionResponse
 */
export class CreateStakePositionResponse extends Message<CreateStakePositionResponse> {
  /**
   * @generated from field: printrfi.api.TxPayload tx_payload = 1;
   */
  txPayload?: TxPayload;

  constructor(data?: PartialMessage<CreateStakePositionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.CreateStakePositionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tx_payload", kind: "message", T: TxPayload },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): CreateStakePositionResponse {
    return new CreateStakePositionResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): CreateStakePositionResponse {
    return new CreateStakePositionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): CreateStakePositionResponse {
    return new CreateStakePositionResponse().fromJsonString(jsonString, options);
  }

  static equals(
    a: CreateStakePositionResponse | PlainMessage<CreateStakePositionResponse> | undefined,
    b: CreateStakePositionResponse | PlainMessage<CreateStakePositionResponse> | undefined,
  ): boolean {
    return proto3.util.equals(CreateStakePositionResponse, a, b);
  }
}
