// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file api/get_buyback_and_burn_detail.proto (package printrfi.api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { Chain } from "../caip/account_pb.js";
import { AssetAmountV1 } from "./misc_pb.js";

/**
 * @generated from message printrfi.api.GetTelecoinDeploymentBuybackAndBurnDetailRequest
 */
export class GetTelecoinDeploymentBuybackAndBurnDetailRequest extends Message<GetTelecoinDeploymentBuybackAndBurnDetailRequest> {
  /**
   * The telecoin identifier.
   *
   * @generated from field: string telecoin_id = 1;
   */
  telecoinId = "";

  /**
   * The chain to get buyback and burn detail for.
   *
   * @generated from field: printrfi.caip.Chain chain = 2;
   */
  chain?: Chain;

  /**
   * Opaque cursor for pagination.
   *
   * The response will include a `next_cursor` field that can be used to fetch the next page of
   * results if there is any.
   *
   * @generated from field: optional string cursor = 3;
   */
  cursor?: string;

  /**
   * @generated from field: optional int32 limit = 4;
   */
  limit?: number;

  constructor(data?: PartialMessage<GetTelecoinDeploymentBuybackAndBurnDetailRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.GetTelecoinDeploymentBuybackAndBurnDetailRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "telecoin_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "chain", kind: "message", T: Chain },
    { no: 3, name: "cursor", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GetTelecoinDeploymentBuybackAndBurnDetailRequest {
    return new GetTelecoinDeploymentBuybackAndBurnDetailRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): GetTelecoinDeploymentBuybackAndBurnDetailRequest {
    return new GetTelecoinDeploymentBuybackAndBurnDetailRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GetTelecoinDeploymentBuybackAndBurnDetailRequest {
    return new GetTelecoinDeploymentBuybackAndBurnDetailRequest().fromJsonString(
      jsonString,
      options,
    );
  }

  static equals(
    a:
      | GetTelecoinDeploymentBuybackAndBurnDetailRequest
      | PlainMessage<GetTelecoinDeploymentBuybackAndBurnDetailRequest>
      | undefined,
    b:
      | GetTelecoinDeploymentBuybackAndBurnDetailRequest
      | PlainMessage<GetTelecoinDeploymentBuybackAndBurnDetailRequest>
      | undefined,
  ): boolean {
    return proto3.util.equals(GetTelecoinDeploymentBuybackAndBurnDetailRequest, a, b);
  }
}

/**
 * @generated from message printrfi.api.GetTelecoinDeploymentBuybackAndBurnDetailResponse
 */
export class GetTelecoinDeploymentBuybackAndBurnDetailResponse extends Message<GetTelecoinDeploymentBuybackAndBurnDetailResponse> {
  /**
   * How many buyback and burn txs have been recorded for the telecoin in total.
   *
   * @generated from field: uint32 total_trades = 1;
   */
  totalTrades = 0;

  /**
   * Sums over all buyback and burn txs.
   *
   * @generated from field: printrfi.api.AssetAmountV1 total_burned = 2;
   */
  totalBurned?: AssetAmountV1;

  /**
   * Sums over all buyback and burn txs.
   *
   * @generated from field: printrfi.api.AssetAmountV1 total_bought_back = 3;
   */
  totalBoughtBack?: AssetAmountV1;

  /**
   * Can be used with the `cursor` field in the request to fetch the next page of results.
   * Will be empty if there are no more results.
   *
   * @generated from field: optional string next_cursor = 4;
   */
  nextCursor?: string;

  /**
   * List of buyback trades, ordered by timestamp in descending order (most recent first).
   *
   * @generated from field: repeated printrfi.api.BuybackAndBurnTx trades = 5;
   */
  trades: BuybackAndBurnTx[] = [];

  constructor(data?: PartialMessage<GetTelecoinDeploymentBuybackAndBurnDetailResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.GetTelecoinDeploymentBuybackAndBurnDetailResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "total_trades", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "total_burned", kind: "message", T: AssetAmountV1 },
    { no: 3, name: "total_bought_back", kind: "message", T: AssetAmountV1 },
    { no: 4, name: "next_cursor", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "trades", kind: "message", T: BuybackAndBurnTx, repeated: true },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GetTelecoinDeploymentBuybackAndBurnDetailResponse {
    return new GetTelecoinDeploymentBuybackAndBurnDetailResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): GetTelecoinDeploymentBuybackAndBurnDetailResponse {
    return new GetTelecoinDeploymentBuybackAndBurnDetailResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GetTelecoinDeploymentBuybackAndBurnDetailResponse {
    return new GetTelecoinDeploymentBuybackAndBurnDetailResponse().fromJsonString(
      jsonString,
      options,
    );
  }

  static equals(
    a:
      | GetTelecoinDeploymentBuybackAndBurnDetailResponse
      | PlainMessage<GetTelecoinDeploymentBuybackAndBurnDetailResponse>
      | undefined,
    b:
      | GetTelecoinDeploymentBuybackAndBurnDetailResponse
      | PlainMessage<GetTelecoinDeploymentBuybackAndBurnDetailResponse>
      | undefined,
  ): boolean {
    return proto3.util.equals(GetTelecoinDeploymentBuybackAndBurnDetailResponse, a, b);
  }
}

/**
 * @generated from message printrfi.api.BuybackAndBurnTx
 */
export class BuybackAndBurnTx extends Message<BuybackAndBurnTx> {
  /**
   * @generated from field: string tx = 1;
   */
  tx = "";

  /**
   * @generated from field: google.protobuf.Timestamp block_timestamp = 2;
   */
  blockTimestamp?: Timestamp;

  /**
   * @generated from field: printrfi.api.AssetAmountV1 burned = 3;
   */
  burned?: AssetAmountV1;

  /**
   * @generated from field: printrfi.api.AssetAmountV1 bought_back = 4;
   */
  boughtBack?: AssetAmountV1;

  constructor(data?: PartialMessage<BuybackAndBurnTx>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.BuybackAndBurnTx";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tx", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "block_timestamp", kind: "message", T: Timestamp },
    { no: 3, name: "burned", kind: "message", T: AssetAmountV1 },
    { no: 4, name: "bought_back", kind: "message", T: AssetAmountV1 },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BuybackAndBurnTx {
    return new BuybackAndBurnTx().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BuybackAndBurnTx {
    return new BuybackAndBurnTx().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BuybackAndBurnTx {
    return new BuybackAndBurnTx().fromJsonString(jsonString, options);
  }

  static equals(
    a: BuybackAndBurnTx | PlainMessage<BuybackAndBurnTx> | undefined,
    b: BuybackAndBurnTx | PlainMessage<BuybackAndBurnTx> | undefined,
  ): boolean {
    return proto3.util.equals(BuybackAndBurnTx, a, b);
  }
}
