// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file api/list_stake_positions.proto (package printrfi.api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { Account } from "../caip/account_pb.js";
import { AssetAmountV1, Bps, SortDirectionV2 } from "./misc_pb.js";
import { StakingLockPeriod } from "./create_stake_position_pb.js";

/**
 * @generated from enum printrfi.api.StakePositionOrderBy
 */
export enum StakePositionOrderBy {
  /**
   * Order by position creation timestamp (default).
   *
   * @generated from enum value: STAKE_POSITION_ORDER_BY_TIMESTAMP = 0;
   */
  TIMESTAMP = 0,

  /**
   * Order by staked amount.
   *
   * @generated from enum value: STAKE_POSITION_ORDER_BY_STAKED_AMOUNT = 1;
   */
  STAKED_AMOUNT = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(StakePositionOrderBy)
proto3.util.setEnumType(StakePositionOrderBy, "printrfi.api.StakePositionOrderBy", [
  { no: 0, name: "STAKE_POSITION_ORDER_BY_TIMESTAMP" },
  { no: 1, name: "STAKE_POSITION_ORDER_BY_STAKED_AMOUNT" },
]);

/**
 * @generated from message printrfi.api.ListStakePositionsRequest
 */
export class ListStakePositionsRequest extends Message<ListStakePositionsRequest> {
  /**
   * Mutually exclusive with `telecoins`.
   *
   * @generated from field: repeated string telecoin_ids = 1;
   */
  telecoinIds: string[] = [];

  /**
   * Mutually exclusive with `telecoin_ids`.
   *
   * @generated from field: repeated printrfi.caip.Account telecoins = 2;
   */
  telecoins: Account[] = [];

  /**
   * @generated from field: repeated printrfi.caip.Account owners = 3;
   */
  owners: Account[] = [];

  /**
   * Opaque cursor for pagination.
   *
   * The response will include a `next_cursor` field that can be used to fetch the next page of
   * results if there is any.
   *
   * @generated from field: optional string cursor = 4;
   */
  cursor?: string;

  /**
   * @generated from field: optional int32 limit = 5;
   */
  limit?: number;

  /**
   * @generated from field: printrfi.api.SortDirectionV2 sort_direction = 6;
   */
  sortDirection = SortDirectionV2.DESC;

  /**
   * Which field to order results by. Defaults to `BY_TIMESTAMP`.
   *
   * @generated from field: printrfi.api.StakePositionOrderBy order_by = 7;
   */
  orderBy = StakePositionOrderBy.TIMESTAMP;

  constructor(data?: PartialMessage<ListStakePositionsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.ListStakePositionsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "telecoin_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "telecoins", kind: "message", T: Account, repeated: true },
    { no: 3, name: "owners", kind: "message", T: Account, repeated: true },
    { no: 4, name: "cursor", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 6, name: "sort_direction", kind: "enum", T: proto3.getEnumType(SortDirectionV2) },
    { no: 7, name: "order_by", kind: "enum", T: proto3.getEnumType(StakePositionOrderBy) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListStakePositionsRequest {
    return new ListStakePositionsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListStakePositionsRequest {
    return new ListStakePositionsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListStakePositionsRequest {
    return new ListStakePositionsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListStakePositionsRequest | PlainMessage<ListStakePositionsRequest> | undefined, b: ListStakePositionsRequest | PlainMessage<ListStakePositionsRequest> | undefined): boolean {
    return proto3.util.equals(ListStakePositionsRequest, a, b);
  }
}

/**
 * @generated from message printrfi.api.ListStakePositionsResponse
 */
export class ListStakePositionsResponse extends Message<ListStakePositionsResponse> {
  /**
   * @generated from field: repeated printrfi.api.StakePositionInfo positions = 1;
   */
  positions: StakePositionInfo[] = [];

  /**
   * Can be used with the `cursor` field in the request to fetch the next page of results.
   * Will be empty if there are no more results.
   *
   * @generated from field: optional string next_cursor = 2;
   */
  nextCursor?: string;

  /**
   * References telecoins that are associated with the returned positions.
   *
   * @generated from field: map<string, printrfi.api.StakeTelecoinInfo> telecoins_by_id = 3;
   */
  telecoinsById: { [key: string]: StakeTelecoinInfo } = {};

  constructor(data?: PartialMessage<ListStakePositionsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.ListStakePositionsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "positions", kind: "message", T: StakePositionInfo, repeated: true },
    { no: 2, name: "next_cursor", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "telecoins_by_id", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: StakeTelecoinInfo} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListStakePositionsResponse {
    return new ListStakePositionsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListStakePositionsResponse {
    return new ListStakePositionsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListStakePositionsResponse {
    return new ListStakePositionsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListStakePositionsResponse | PlainMessage<ListStakePositionsResponse> | undefined, b: ListStakePositionsResponse | PlainMessage<ListStakePositionsResponse> | undefined): boolean {
    return proto3.util.equals(ListStakePositionsResponse, a, b);
  }
}

/**
 * @generated from message printrfi.api.ListStakePositionsWithRewardsResponse
 */
export class ListStakePositionsWithRewardsResponse extends Message<ListStakePositionsWithRewardsResponse> {
  /**
   * @generated from field: repeated printrfi.api.StakePositionWithRewardsInfo positions = 1;
   */
  positions: StakePositionWithRewardsInfo[] = [];

  /**
   * Can be used with the `cursor` field in the request to fetch the next page of results.
   * Will be empty if there are no more results.
   *
   * @generated from field: optional string next_cursor = 2;
   */
  nextCursor?: string;

  /**
   * References telecoins that are associated with the returned positions.
   *
   * @generated from field: map<string, printrfi.api.StakeTelecoinInfo> telecoins_by_id = 3;
   */
  telecoinsById: { [key: string]: StakeTelecoinInfo } = {};

  constructor(data?: PartialMessage<ListStakePositionsWithRewardsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.ListStakePositionsWithRewardsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "positions", kind: "message", T: StakePositionWithRewardsInfo, repeated: true },
    { no: 2, name: "next_cursor", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "telecoins_by_id", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: StakeTelecoinInfo} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListStakePositionsWithRewardsResponse {
    return new ListStakePositionsWithRewardsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListStakePositionsWithRewardsResponse {
    return new ListStakePositionsWithRewardsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListStakePositionsWithRewardsResponse {
    return new ListStakePositionsWithRewardsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListStakePositionsWithRewardsResponse | PlainMessage<ListStakePositionsWithRewardsResponse> | undefined, b: ListStakePositionsWithRewardsResponse | PlainMessage<ListStakePositionsWithRewardsResponse> | undefined): boolean {
    return proto3.util.equals(ListStakePositionsWithRewardsResponse, a, b);
  }
}

/**
 * @generated from message printrfi.api.StakeTelecoinInfo
 */
export class StakeTelecoinInfo extends Message<StakeTelecoinInfo> {
  /**
   * A telecoin can have multiple stake pools, at most one per a chain though.
   *
   * @generated from field: repeated printrfi.api.StakePoolInfo stake_pools_per_chain = 1;
   */
  stakePoolsPerChain: StakePoolInfo[] = [];

  constructor(data?: PartialMessage<StakeTelecoinInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.StakeTelecoinInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "stake_pools_per_chain", kind: "message", T: StakePoolInfo, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StakeTelecoinInfo {
    return new StakeTelecoinInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StakeTelecoinInfo {
    return new StakeTelecoinInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StakeTelecoinInfo {
    return new StakeTelecoinInfo().fromJsonString(jsonString, options);
  }

  static equals(a: StakeTelecoinInfo | PlainMessage<StakeTelecoinInfo> | undefined, b: StakeTelecoinInfo | PlainMessage<StakeTelecoinInfo> | undefined): boolean {
    return proto3.util.equals(StakeTelecoinInfo, a, b);
  }
}

/**
 * @generated from message printrfi.api.StakePoolInfo
 */
export class StakePoolInfo extends Message<StakePoolInfo> {
  /**
   * Telecoin's stake pool account on a specific chain.
   * Can be used to highlight the stake pool in the holders table.
   *
   * @generated from field: printrfi.caip.Account stake_pool = 1;
   */
  stakePool?: Account;

  /**
   * Up-to-date total weight of the telecoin's stake pool.
   *
   * @generated from field: string total_weight = 2;
   */
  totalWeight = "";

  /**
   * How many open positions are currently in the telecoin's stake pool.
   * Includes also unlocked positions that haven't been closed yet.
   * This number is cached and can be stale.
   *
   * @generated from field: uint32 total_open_positions = 3;
   */
  totalOpenPositions = 0;

  /**
   * Total weight of all unlocked positions in the telecoin's stake pool.
   *
   * @generated from field: string total_unlocked_weight = 4;
   */
  totalUnlockedWeight = "";

  /**
   * Total staked supply (unweighted) across all open positions.
   *
   * @generated from field: printrfi.api.AssetAmountV1 total_staked = 5;
   */
  totalStaked?: AssetAmountV1;

  /**
   * Total staked supply (unweighted) across unlocked positions only.
   *
   * @generated from field: printrfi.api.AssetAmountV1 total_unlocked_staked = 6;
   */
  totalUnlockedStaked?: AssetAmountV1;

  constructor(data?: PartialMessage<StakePoolInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.StakePoolInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "stake_pool", kind: "message", T: Account },
    { no: 2, name: "total_weight", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "total_open_positions", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "total_unlocked_weight", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "total_staked", kind: "message", T: AssetAmountV1 },
    { no: 6, name: "total_unlocked_staked", kind: "message", T: AssetAmountV1 },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StakePoolInfo {
    return new StakePoolInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StakePoolInfo {
    return new StakePoolInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StakePoolInfo {
    return new StakePoolInfo().fromJsonString(jsonString, options);
  }

  static equals(a: StakePoolInfo | PlainMessage<StakePoolInfo> | undefined, b: StakePoolInfo | PlainMessage<StakePoolInfo> | undefined): boolean {
    return proto3.util.equals(StakePoolInfo, a, b);
  }
}

/**
 * @generated from message printrfi.api.StakePositionInfo
 */
export class StakePositionInfo extends Message<StakePositionInfo> {
  /**
   * @generated from field: string telecoin_id = 1;
   */
  telecoinId = "";

  /**
   * @generated from field: printrfi.caip.Account owner = 2;
   */
  owner?: Account;

  /**
   * @generated from field: printrfi.caip.Account position = 3;
   */
  position?: Account;

  /**
   * @generated from field: printrfi.api.StakingLockPeriod lock_period = 4;
   */
  lockPeriod = StakingLockPeriod.UNSPECIFIED;

  /**
   * @generated from field: printrfi.api.AssetAmountV1 staked = 5;
   */
  staked?: AssetAmountV1;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp unlocks_at = 7;
   */
  unlocksAt?: Timestamp;

  /**
   * @generated from field: bool was_closed = 8;
   */
  wasClosed = false;

  /**
   * @generated from field: string creation_tx = 9;
   */
  creationTx = "";

  /**
   * Share of the telecoin's stake pool that this position represents.
   * 0 means less than 1 bps (floors down).
   *
   * @generated from field: printrfi.api.Bps share_in_stake_pool = 10;
   */
  shareInStakePool?: Bps;

  constructor(data?: PartialMessage<StakePositionInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.StakePositionInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "telecoin_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "owner", kind: "message", T: Account },
    { no: 3, name: "position", kind: "message", T: Account },
    { no: 4, name: "lock_period", kind: "enum", T: proto3.getEnumType(StakingLockPeriod) },
    { no: 5, name: "staked", kind: "message", T: AssetAmountV1 },
    { no: 6, name: "created_at", kind: "message", T: Timestamp },
    { no: 7, name: "unlocks_at", kind: "message", T: Timestamp },
    { no: 8, name: "was_closed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "creation_tx", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "share_in_stake_pool", kind: "message", T: Bps },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StakePositionInfo {
    return new StakePositionInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StakePositionInfo {
    return new StakePositionInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StakePositionInfo {
    return new StakePositionInfo().fromJsonString(jsonString, options);
  }

  static equals(a: StakePositionInfo | PlainMessage<StakePositionInfo> | undefined, b: StakePositionInfo | PlainMessage<StakePositionInfo> | undefined): boolean {
    return proto3.util.equals(StakePositionInfo, a, b);
  }
}

/**
 * @generated from message printrfi.api.StakePositionWithRewardsInfo
 */
export class StakePositionWithRewardsInfo extends Message<StakePositionWithRewardsInfo> {
  /**
   * @generated from field: printrfi.api.StakePositionInfo info = 1;
   */
  info?: StakePositionInfo;

  /**
   * @generated from field: optional printrfi.api.AssetAmountV1 claimable_quote_rewards = 2;
   */
  claimableQuoteRewards?: AssetAmountV1;

  /**
   * @generated from field: optional printrfi.api.AssetAmountV1 claimable_telecoin_rewards = 3;
   */
  claimableTelecoinRewards?: AssetAmountV1;

  /**
   * @generated from field: optional printrfi.api.AssetAmountV1 claimed_quote_rewards = 4;
   */
  claimedQuoteRewards?: AssetAmountV1;

  /**
   * @generated from field: optional printrfi.api.AssetAmountV1 claimed_telecoin_rewards = 5;
   */
  claimedTelecoinRewards?: AssetAmountV1;

  constructor(data?: PartialMessage<StakePositionWithRewardsInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.StakePositionWithRewardsInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "info", kind: "message", T: StakePositionInfo },
    { no: 2, name: "claimable_quote_rewards", kind: "message", T: AssetAmountV1, opt: true },
    { no: 3, name: "claimable_telecoin_rewards", kind: "message", T: AssetAmountV1, opt: true },
    { no: 4, name: "claimed_quote_rewards", kind: "message", T: AssetAmountV1, opt: true },
    { no: 5, name: "claimed_telecoin_rewards", kind: "message", T: AssetAmountV1, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StakePositionWithRewardsInfo {
    return new StakePositionWithRewardsInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StakePositionWithRewardsInfo {
    return new StakePositionWithRewardsInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StakePositionWithRewardsInfo {
    return new StakePositionWithRewardsInfo().fromJsonString(jsonString, options);
  }

  static equals(a: StakePositionWithRewardsInfo | PlainMessage<StakePositionWithRewardsInfo> | undefined, b: StakePositionWithRewardsInfo | PlainMessage<StakePositionWithRewardsInfo> | undefined): boolean {
    return proto3.util.equals(StakePositionWithRewardsInfo, a, b);
  }
}

