// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file api/quote_spend_on_telecoin.proto (package printrfi.api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Chain } from "../caip/account_pb.js";
import { AssetAmountV1, PricedAsset } from "./misc_pb.js";

/**
 * @generated from message printrfi.api.QuoteSpendOnTelecoinRequest
 */
export class QuoteSpendOnTelecoinRequest extends Message<QuoteSpendOnTelecoinRequest> {
  /**
   * @generated from field: string telecoin_id = 1;
   */
  telecoinId = "";

  /**
   * @generated from field: printrfi.api.AssetAmountV1 spend_on_source = 2;
   */
  spendOnSource?: AssetAmountV1;

  /**
   * @generated from field: printrfi.caip.Chain destination = 3;
   */
  destination?: Chain;

  constructor(data?: PartialMessage<QuoteSpendOnTelecoinRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.QuoteSpendOnTelecoinRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "telecoin_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "spend_on_source", kind: "message", T: AssetAmountV1 },
    { no: 3, name: "destination", kind: "message", T: Chain },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): QuoteSpendOnTelecoinRequest {
    return new QuoteSpendOnTelecoinRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): QuoteSpendOnTelecoinRequest {
    return new QuoteSpendOnTelecoinRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): QuoteSpendOnTelecoinRequest {
    return new QuoteSpendOnTelecoinRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a: QuoteSpendOnTelecoinRequest | PlainMessage<QuoteSpendOnTelecoinRequest> | undefined,
    b: QuoteSpendOnTelecoinRequest | PlainMessage<QuoteSpendOnTelecoinRequest> | undefined,
  ): boolean {
    return proto3.util.equals(QuoteSpendOnTelecoinRequest, a, b);
  }
}

/**
 * @generated from message printrfi.api.QuoteSpendOnTelecoinResponse
 */
export class QuoteSpendOnTelecoinResponse extends Message<QuoteSpendOnTelecoinResponse> {
  /**
   * Might not be equal to the requested spend amount, could be less or more.
   * We make best effort to match the requested amount.
   *
   * @generated from field: printrfi.api.AssetAmountV1 spend_on_source = 1;
   */
  spendOnSource?: AssetAmountV1;

  /**
   * @generated from field: printrfi.api.AssetAmountV1 receive_telecoin_on_destination = 2;
   */
  receiveTelecoinOnDestination?: AssetAmountV1;

  /**
   * Will be equal to `spend_input_on_source` for same-chain quotes.
   *
   * @generated from field: printrfi.api.AssetAmountV1 spend_quote_on_destination = 3;
   */
  spendQuoteOnDestination?: AssetAmountV1;

  /**
   * The effective price after the swap in telecoin/quote.
   *
   * @generated from field: printrfi.api.PricedAsset effective_price = 4;
   */
  effectivePrice?: PricedAsset;

  constructor(data?: PartialMessage<QuoteSpendOnTelecoinResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.QuoteSpendOnTelecoinResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "spend_on_source", kind: "message", T: AssetAmountV1 },
    { no: 2, name: "receive_telecoin_on_destination", kind: "message", T: AssetAmountV1 },
    { no: 3, name: "spend_quote_on_destination", kind: "message", T: AssetAmountV1 },
    { no: 4, name: "effective_price", kind: "message", T: PricedAsset },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): QuoteSpendOnTelecoinResponse {
    return new QuoteSpendOnTelecoinResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): QuoteSpendOnTelecoinResponse {
    return new QuoteSpendOnTelecoinResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): QuoteSpendOnTelecoinResponse {
    return new QuoteSpendOnTelecoinResponse().fromJsonString(jsonString, options);
  }

  static equals(
    a: QuoteSpendOnTelecoinResponse | PlainMessage<QuoteSpendOnTelecoinResponse> | undefined,
    b: QuoteSpendOnTelecoinResponse | PlainMessage<QuoteSpendOnTelecoinResponse> | undefined,
  ): boolean {
    return proto3.util.equals(QuoteSpendOnTelecoinResponse, a, b);
  }
}
