// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file api/spend_on_telecoin.proto (package printrfi.api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Account } from "../caip/account_pb.js";
import { AssetAmountV1, PricedAsset } from "./misc_pb.js";
import { TxPayload } from "./payload_pb.js";

/**
 * @generated from message printrfi.api.SpendOnTelecoinRequest
 */
export class SpendOnTelecoinRequest extends Message<SpendOnTelecoinRequest> {
  /**
   * @generated from field: string telecoin_id = 1;
   */
  telecoinId = "";

  /**
   * @generated from field: printrfi.caip.Account source_spender = 2;
   */
  sourceSpender?: Account;

  /**
   * @generated from field: printrfi.api.AssetAmountV1 spend_on_source = 3;
   */
  spendOnSource?: AssetAmountV1;

  /**
   * @generated from field: printrfi.caip.Account destination_receiver = 4;
   */
  destinationReceiver?: Account;

  /**
   * @generated from oneof printrfi.api.SpendOnTelecoinRequest.slippage
   */
  slippage: {
    /**
     * Calculated on top of the latest price known to Printr.
     *
     * @generated from field: uint32 bps_on_current_price = 5;
     */
    value: number;
    case: "bpsOnCurrentPrice";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<SpendOnTelecoinRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.SpendOnTelecoinRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "telecoin_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "source_spender", kind: "message", T: Account },
    { no: 3, name: "spend_on_source", kind: "message", T: AssetAmountV1 },
    { no: 4, name: "destination_receiver", kind: "message", T: Account },
    { no: 5, name: "bps_on_current_price", kind: "scalar", T: 13 /* ScalarType.UINT32 */, oneof: "slippage" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SpendOnTelecoinRequest {
    return new SpendOnTelecoinRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SpendOnTelecoinRequest {
    return new SpendOnTelecoinRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SpendOnTelecoinRequest {
    return new SpendOnTelecoinRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SpendOnTelecoinRequest | PlainMessage<SpendOnTelecoinRequest> | undefined, b: SpendOnTelecoinRequest | PlainMessage<SpendOnTelecoinRequest> | undefined): boolean {
    return proto3.util.equals(SpendOnTelecoinRequest, a, b);
  }
}

/**
 * @generated from message printrfi.api.SpendOnTelecoinResponse
 */
export class SpendOnTelecoinResponse extends Message<SpendOnTelecoinResponse> {
  /**
   * Might not be equal to the requested spend amount, could be less or more.
   * We make best effort to match the requested amount.
   *
   * @generated from field: printrfi.api.AssetAmountV1 spend_on_source = 1;
   */
  spendOnSource?: AssetAmountV1;

  /**
   * @generated from field: printrfi.api.AssetAmountV1 receive_telecoin_on_destination = 2;
   */
  receiveTelecoinOnDestination?: AssetAmountV1;

  /**
   * Will be equal to `spend_input_on_source` for same-chain quotes.
   *
   * @generated from field: printrfi.api.AssetAmountV1 spend_quote_on_destination = 3;
   */
  spendQuoteOnDestination?: AssetAmountV1;

  /**
   * The effective price after the swap in telecoin/quote.
   *
   * @generated from field: printrfi.api.PricedAsset effective_price = 4;
   */
  effectivePrice?: PricedAsset;

  /**
   * Execute this payload to perform the spend.
   *
   * @generated from field: printrfi.api.TxPayload tx_payload = 5;
   */
  txPayload?: TxPayload;

  constructor(data?: PartialMessage<SpendOnTelecoinResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.api.SpendOnTelecoinResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "spend_on_source", kind: "message", T: AssetAmountV1 },
    { no: 2, name: "receive_telecoin_on_destination", kind: "message", T: AssetAmountV1 },
    { no: 3, name: "spend_quote_on_destination", kind: "message", T: AssetAmountV1 },
    { no: 4, name: "effective_price", kind: "message", T: PricedAsset },
    { no: 5, name: "tx_payload", kind: "message", T: TxPayload },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SpendOnTelecoinResponse {
    return new SpendOnTelecoinResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SpendOnTelecoinResponse {
    return new SpendOnTelecoinResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SpendOnTelecoinResponse {
    return new SpendOnTelecoinResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SpendOnTelecoinResponse | PlainMessage<SpendOnTelecoinResponse> | undefined, b: SpendOnTelecoinResponse | PlainMessage<SpendOnTelecoinResponse> | undefined): boolean {
    return proto3.util.equals(SpendOnTelecoinResponse, a, b);
  }
}

