// Generated by scripts/gen-chains.ts from @printr/sdk CHAIN_META. Do not edit.
export type SupportedChain = { caip2: string; name: string; symbol: string; decimals: number };

export const SUPPORTED_CHAINS: readonly SupportedChain[] = [
  {
    "caip2": "eip155:1",
    "name": "Ethereum",
    "symbol": "ETH",
    "decimals": 18
  },
  {
    "caip2": "eip155:56",
    "name": "BNB",
    "symbol": "BNB",
    "decimals": 18
  },
  {
    "caip2": "eip155:130",
    "name": "Unichain",
    "symbol": "ETH",
    "decimals": 18
  },
  {
    "caip2": "eip155:143",
    "name": "Monad",
    "symbol": "MON",
    "decimals": 18
  },
  {
    "caip2": "eip155:999",
    "name": "HyperEVM",
    "symbol": "HYPE",
    "decimals": 18
  },
  {
    "caip2": "eip155:5000",
    "name": "Mantle",
    "symbol": "MNT",
    "decimals": 18
  },
  {
    "caip2": "eip155:4326",
    "name": "MegaETH",
    "symbol": "ETH",
    "decimals": 18
  },
  {
    "caip2": "eip155:4663",
    "name": "Robinhood",
    "symbol": "ETH",
    "decimals": 18
  },
  {
    "caip2": "eip155:8453",
    "name": "Base",
    "symbol": "ETH",
    "decimals": 18
  },
  {
    "caip2": "eip155:9745",
    "name": "Plasma",
    "symbol": "XPL",
    "decimals": 18
  },
  {
    "caip2": "eip155:42161",
    "name": "Arbitrum",
    "symbol": "ETH",
    "decimals": 18
  },
  {
    "caip2": "eip155:43114",
    "name": "Avalanche",
    "symbol": "AVAX",
    "decimals": 18
  },
  {
    "caip2": "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp",
    "name": "Solana",
    "symbol": "SOL",
    "decimals": 9
  }
];
