#!/usr/bin/env bun
/**
 * Generate the supported-chains table data from the SDK's `CHAIN_META` so the
 * docs can never drift from the source of truth. Reads from `@printr/sdk`
 * source directly (no build step needed) and writes `lib/chains.generated.ts`.
 * Wired into the docs `build` and `typecheck` scripts.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { CHAIN_META } from "../../../packages/sdk/src/chains.js";

type Row = { caip2: string; name: string; symbol: string; decimals: number };

// CHAIN_META is keyed by both CAIP-2 ids ("eip155:1", "solana:…") and lowercase
// aliases ("eth", "bsc", …). Keep only the canonical CAIP-2 keys for the table.
const rows: Row[] = Object.entries(CHAIN_META)
  .filter(([key]) => key.includes(":"))
  .map(([caip2, meta]) => ({
    caip2,
    name: meta.name,
    symbol: meta.symbol,
    decimals: meta.decimals,
  }));

const out = `// Generated by scripts/gen-chains.ts from @printr/sdk CHAIN_META. Do not edit.
export type SupportedChain = { caip2: string; name: string; symbol: string; decimals: number };

export const SUPPORTED_CHAINS: readonly SupportedChain[] = ${JSON.stringify(rows, null, 2)};
`;

const dest = resolve(import.meta.dir, "../lib/chains.generated.ts");
writeFileSync(dest, out);
console.log(`Wrote ${rows.length} chains to ${dest}`);
