// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file wingman/solana_claim_staking_rewards.proto (package printrfi.wingman, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Base58Pubkey, SolanaIx } from "./misc_pb.js";

/**
 * @generated from message printrfi.wingman.SolanaClaimStakingRewardsRequest
 */
export class SolanaClaimStakingRewardsRequest extends Message<SolanaClaimStakingRewardsRequest> {
  /**
   * Who pays for the transaction and owns the stake position.
   * The tx that submits the returned ixs must be signed by this account.
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey payer = 1;
   */
  payer?: Base58Pubkey;

  /**
   * The Printr token ID as hex string.
   *
   * Required.
   *
   * @generated from field: string printr_token_id = 2;
   */
  printrTokenId = "";

  /**
   * Identifies which position to claim from.
   *
   * Required.
   *
   * @generated from field: uint32 position_nonce = 3;
   */
  positionNonce = 0;

  constructor(data?: PartialMessage<SolanaClaimStakingRewardsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaClaimStakingRewardsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "payer", kind: "message", T: Base58Pubkey },
    { no: 2, name: "printr_token_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "position_nonce", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): SolanaClaimStakingRewardsRequest {
    return new SolanaClaimStakingRewardsRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): SolanaClaimStakingRewardsRequest {
    return new SolanaClaimStakingRewardsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): SolanaClaimStakingRewardsRequest {
    return new SolanaClaimStakingRewardsRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a:
      | SolanaClaimStakingRewardsRequest
      | PlainMessage<SolanaClaimStakingRewardsRequest>
      | undefined,
    b:
      | SolanaClaimStakingRewardsRequest
      | PlainMessage<SolanaClaimStakingRewardsRequest>
      | undefined,
  ): boolean {
    return proto3.util.equals(SolanaClaimStakingRewardsRequest, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.SolanaClaimStakingRewardsResponse
 */
export class SolanaClaimStakingRewardsResponse extends Message<SolanaClaimStakingRewardsResponse> {
  /**
   * The ixs with which to build a tx.
   *
   * Required.
   *
   * @generated from field: repeated printrfi.wingman.SolanaIx ixs = 1;
   */
  ixs: SolanaIx[] = [];

  /**
   * Use this lookup table to minimize the tx size.
   *
   * Optional.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey lookup_table = 2;
   */
  lookupTable?: Base58Pubkey;

  constructor(data?: PartialMessage<SolanaClaimStakingRewardsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaClaimStakingRewardsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ixs", kind: "message", T: SolanaIx, repeated: true },
    { no: 2, name: "lookup_table", kind: "message", T: Base58Pubkey },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): SolanaClaimStakingRewardsResponse {
    return new SolanaClaimStakingRewardsResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): SolanaClaimStakingRewardsResponse {
    return new SolanaClaimStakingRewardsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): SolanaClaimStakingRewardsResponse {
    return new SolanaClaimStakingRewardsResponse().fromJsonString(jsonString, options);
  }

  static equals(
    a:
      | SolanaClaimStakingRewardsResponse
      | PlainMessage<SolanaClaimStakingRewardsResponse>
      | undefined,
    b:
      | SolanaClaimStakingRewardsResponse
      | PlainMessage<SolanaClaimStakingRewardsResponse>
      | undefined,
  ): boolean {
    return proto3.util.equals(SolanaClaimStakingRewardsResponse, a, b);
  }
}
