// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file wingman/solana_swap.proto (package printrfi.wingman, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Base58Pubkey, PrintrProtocolVersion, SolanaIx } from "./misc_pb.js";

/**
 * Determines what should happen and gives semantic meaning to the two amounts
 * in the SolanaSwapRequest message.
 *
 * @generated from enum printrfi.wingman.SwapIntent
 */
export enum SwapIntent {
  /**
   * Not supported atm.
   *
   * @generated from enum value: BUY_TELECOIN = 0;
   */
  BUY_TELECOIN = 0,

  /**
   * @generated from enum value: SELL_TELECOIN = 1;
   */
  SELL_TELECOIN = 1,

  /**
   * @generated from enum value: SPEND_QUOTE = 2;
   */
  SPEND_QUOTE = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(SwapIntent)
proto3.util.setEnumType(SwapIntent, "printrfi.wingman.SwapIntent", [
  { no: 0, name: "BUY_TELECOIN" },
  { no: 1, name: "SELL_TELECOIN" },
  { no: 2, name: "SPEND_QUOTE" },
]);

/**
 * @generated from message printrfi.wingman.SolanaSwapRequest
 */
export class SolanaSwapRequest extends Message<SolanaSwapRequest> {
  /**
   * The user that will sign the transaction.
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey payer = 1;
   */
  payer?: Base58Pubkey;

  /**
   * The Printr interchain token ID as hex string.
   *
   * Required.
   *
   * @generated from field: string printr_token_id = 2;
   */
  printrTokenId = "";

  /**
   * The swap direction.
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.SwapIntent intent = 3;
   */
  intent = SwapIntent.BUY_TELECOIN;

  /**
   * Sell amount or buy amount, depending on the intent.
   *
   * Required.
   *
   * @generated from field: uint64 amount = 4;
   */
  amount = protoInt64.zero;

  /**
   * Slippage on price in basis points to use when calculating the amount.
   * We calculate the slippage amount by changing the current price by this
   * percentage and then multiplying it by the amount.
   *
   * Optional, defaults to 0%.
   *
   * @generated from field: uint64 price_slippage_bps = 6;
   */
  priceSlippageBps = protoInt64.zero;

  /**
   * / The Printr protocol version associated with the token.
   *
   * @generated from field: printrfi.wingman.PrintrProtocolVersion token_protocol_version = 7;
   */
  tokenProtocolVersion?: PrintrProtocolVersion;

  constructor(data?: PartialMessage<SolanaSwapRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaSwapRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "payer", kind: "message", T: Base58Pubkey },
    { no: 2, name: "printr_token_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "intent", kind: "enum", T: proto3.getEnumType(SwapIntent) },
    { no: 4, name: "amount", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 6, name: "price_slippage_bps", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 7, name: "token_protocol_version", kind: "message", T: PrintrProtocolVersion },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SolanaSwapRequest {
    return new SolanaSwapRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SolanaSwapRequest {
    return new SolanaSwapRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SolanaSwapRequest {
    return new SolanaSwapRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SolanaSwapRequest | PlainMessage<SolanaSwapRequest> | undefined, b: SolanaSwapRequest | PlainMessage<SolanaSwapRequest> | undefined): boolean {
    return proto3.util.equals(SolanaSwapRequest, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.SolanaSwapResponse
 */
export class SolanaSwapResponse extends Message<SolanaSwapResponse> {
  /**
   * The ixs with which to build a tx
   *
   * Required.
   *
   * @generated from field: repeated printrfi.wingman.SolanaIx ixs = 1;
   */
  ixs: SolanaIx[] = [];

  /**
   * Use this lookup table to minimize the tx size
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey lookup_table = 2;
   */
  lookupTable?: Base58Pubkey;

  /**
   * How much will the user spend in the token that goes into a bonding curve/pool.
   *
   * Required.
   *
   * @generated from field: uint64 amount_in = 3;
   */
  amountIn = protoInt64.zero;

  /**
   * How much will the user receive in the token that comes out of a bonding curve/pool.
   *
   * Required.
   *
   * @generated from field: uint64 amount_out = 4;
   */
  amountOut = protoInt64.zero;

  /**
   * Had the user submitted this calldata, they should expect this final price.
   * This is useful to inform the user that their swap is likely to fail due to price slippage.
   * That's because the calldata still honour the price slippage argument.
   *
   * Required.
   *
   * @generated from field: string final_price_display = 5;
   */
  finalPriceDisplay = "";

  constructor(data?: PartialMessage<SolanaSwapResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaSwapResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ixs", kind: "message", T: SolanaIx, repeated: true },
    { no: 2, name: "lookup_table", kind: "message", T: Base58Pubkey },
    { no: 3, name: "amount_in", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "amount_out", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "final_price_display", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SolanaSwapResponse {
    return new SolanaSwapResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SolanaSwapResponse {
    return new SolanaSwapResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SolanaSwapResponse {
    return new SolanaSwapResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SolanaSwapResponse | PlainMessage<SolanaSwapResponse> | undefined, b: SolanaSwapResponse | PlainMessage<SolanaSwapResponse> | undefined): boolean {
    return proto3.util.equals(SolanaSwapResponse, a, b);
  }
}

