// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file wingman/solana_lz_bridge.proto (package printrfi.wingman, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Base58Pubkey, SolanaIx, TokenAmount } from "./misc_pb.js";
import { Account } from "../caip/account_pb.js";

/**
 * @generated from message printrfi.wingman.SolanaLzBridgeRequest
 */
export class SolanaLzBridgeRequest extends Message<SolanaLzBridgeRequest> {
  /**
   * The user that will sign the transaction.
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey payer = 1;
   */
  payer?: Base58Pubkey;

  /**
   * The Printr interchain token ID as hex string.
   *
   * Required.
   *
   * @generated from field: string printr_token_id = 2;
   */
  printrTokenId = "";

  /**
   * telecoin token amount to teleport.
   *
   * Required.
   *
   * @generated from field: uint64 amount_atomic = 3;
   */
  amountAtomic = protoInt64.zero;

  /**
   * The destination recipient.
   * Determines where the bridged tokens will end up.
   *
   * Required.
   *
   * @generated from field: printrfi.caip.Account recipient = 4;
   */
  recipient?: Account;

  /**
   * The gas fee for the destination chain, in atomic units.
   *
   * Required.
   *
   * @generated from field: string destination_gas_fee_atomic = 5;
   */
  destinationGasFeeAtomic = "";

  constructor(data?: PartialMessage<SolanaLzBridgeRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaLzBridgeRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "payer", kind: "message", T: Base58Pubkey },
    { no: 2, name: "printr_token_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "amount_atomic", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "recipient", kind: "message", T: Account },
    { no: 5, name: "destination_gas_fee_atomic", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SolanaLzBridgeRequest {
    return new SolanaLzBridgeRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SolanaLzBridgeRequest {
    return new SolanaLzBridgeRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SolanaLzBridgeRequest {
    return new SolanaLzBridgeRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SolanaLzBridgeRequest | PlainMessage<SolanaLzBridgeRequest> | undefined, b: SolanaLzBridgeRequest | PlainMessage<SolanaLzBridgeRequest> | undefined): boolean {
    return proto3.util.equals(SolanaLzBridgeRequest, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.SolanaLzBridgeResponse
 */
export class SolanaLzBridgeResponse extends Message<SolanaLzBridgeResponse> {
  /**
   * The ixs with which to build a tx.
   *
   * Required.
   *
   * @generated from field: repeated printrfi.wingman.SolanaIx ixs = 1;
   */
  ixs: SolanaIx[] = [];

  /**
   * Use this lookup table to minimize the tx size.
   *
   * Optional.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey lookup_table = 2;
   */
  lookupTable?: Base58Pubkey;

  /**
   * How much will the user spend on xchain fee, ie. how much does LZ charge.
   *
   * @generated from field: printrfi.wingman.TokenAmount xchain_fee_cost = 3;
   */
  xchainFeeCost?: TokenAmount;

  /**
   * How much will the user spend on the tx.
   *
   * @generated from field: printrfi.wingman.TokenAmount source_gas_cost = 4;
   */
  sourceGasCost?: TokenAmount;

  constructor(data?: PartialMessage<SolanaLzBridgeResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaLzBridgeResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ixs", kind: "message", T: SolanaIx, repeated: true },
    { no: 2, name: "lookup_table", kind: "message", T: Base58Pubkey },
    { no: 3, name: "xchain_fee_cost", kind: "message", T: TokenAmount },
    { no: 4, name: "source_gas_cost", kind: "message", T: TokenAmount },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SolanaLzBridgeResponse {
    return new SolanaLzBridgeResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SolanaLzBridgeResponse {
    return new SolanaLzBridgeResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SolanaLzBridgeResponse {
    return new SolanaLzBridgeResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SolanaLzBridgeResponse | PlainMessage<SolanaLzBridgeResponse> | undefined, b: SolanaLzBridgeResponse | PlainMessage<SolanaLzBridgeResponse> | undefined): boolean {
    return proto3.util.equals(SolanaLzBridgeResponse, a, b);
  }
}

