// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file wingman/solana_claim_fees.proto (package printrfi.wingman, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Base58Pubkey, PrintrProtocolVersion, SolanaIx, TokenAmount } from "./misc_pb.js";

/**
 * @generated from message printrfi.wingman.SolanaClaimFeesRequest
 */
export class SolanaClaimFeesRequest extends Message<SolanaClaimFeesRequest> {
  /**
   * Who pays for the rent, typically the user's pubkey.
   * The tx that submits the returned ixs must be signed by this account.
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey payer = 1;
   */
  payer?: Base58Pubkey;

  /**
   * The Printr token ID as hex string.
   *
   * Required.
   *
   * @generated from field: string printr_token_id = 2;
   */
  printrTokenId = "";

  /**
   * The creator of the bonding curve on Solana.
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey creator_on_solana = 3;
   */
  creatorOnSolana?: Base58Pubkey;

  /**
   * / The Printr protocol version associated with the token.
   *
   * @generated from field: printrfi.wingman.PrintrProtocolVersion token_protocol_version = 4;
   */
  tokenProtocolVersion?: PrintrProtocolVersion;

  constructor(data?: PartialMessage<SolanaClaimFeesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaClaimFeesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "payer", kind: "message", T: Base58Pubkey },
    { no: 2, name: "printr_token_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "creator_on_solana", kind: "message", T: Base58Pubkey },
    { no: 4, name: "token_protocol_version", kind: "message", T: PrintrProtocolVersion },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): SolanaClaimFeesRequest {
    return new SolanaClaimFeesRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): SolanaClaimFeesRequest {
    return new SolanaClaimFeesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): SolanaClaimFeesRequest {
    return new SolanaClaimFeesRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a: SolanaClaimFeesRequest | PlainMessage<SolanaClaimFeesRequest> | undefined,
    b: SolanaClaimFeesRequest | PlainMessage<SolanaClaimFeesRequest> | undefined,
  ): boolean {
    return proto3.util.equals(SolanaClaimFeesRequest, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.SolanaClaimFeesResponse
 */
export class SolanaClaimFeesResponse extends Message<SolanaClaimFeesResponse> {
  /**
   * The ixs with which to build a tx.
   *
   * Required.
   *
   * @generated from field: repeated printrfi.wingman.SolanaIx ixs = 1;
   */
  ixs: SolanaIx[] = [];

  /**
   * Use this lookup table to minimize the tx size
   *
   * Optional.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey lookup_table = 2;
   */
  lookupTable?: Base58Pubkey;

  /**
   * How much will creator receive in quote token.
   *
   * @generated from field: printrfi.wingman.TokenAmount creator_on_solana_expected_quote = 4;
   */
  creatorOnSolanaExpectedQuote?: TokenAmount;

  /**
   * How much will creator receive in telecoin.
   *
   * @generated from field: printrfi.wingman.TokenAmount creator_on_solana_expected_telecoin = 5;
   */
  creatorOnSolanaExpectedTelecoin?: TokenAmount;

  /**
   * How much will the user spend on the tx.
   *
   * @generated from field: printrfi.wingman.TokenAmount source_gas_cost = 6;
   */
  sourceGasCost?: TokenAmount;

  constructor(data?: PartialMessage<SolanaClaimFeesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaClaimFeesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ixs", kind: "message", T: SolanaIx, repeated: true },
    { no: 2, name: "lookup_table", kind: "message", T: Base58Pubkey },
    { no: 4, name: "creator_on_solana_expected_quote", kind: "message", T: TokenAmount },
    { no: 5, name: "creator_on_solana_expected_telecoin", kind: "message", T: TokenAmount },
    { no: 6, name: "source_gas_cost", kind: "message", T: TokenAmount },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): SolanaClaimFeesResponse {
    return new SolanaClaimFeesResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): SolanaClaimFeesResponse {
    return new SolanaClaimFeesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): SolanaClaimFeesResponse {
    return new SolanaClaimFeesResponse().fromJsonString(jsonString, options);
  }

  static equals(
    a: SolanaClaimFeesResponse | PlainMessage<SolanaClaimFeesResponse> | undefined,
    b: SolanaClaimFeesResponse | PlainMessage<SolanaClaimFeesResponse> | undefined,
  ): boolean {
    return proto3.util.equals(SolanaClaimFeesResponse, a, b);
  }
}
