// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file wingman/solana_print_from_evm.proto (package printrfi.wingman, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { EvmTx, QuotedEvmTx, TelecoinInstance, TelecoinParams, TxInfo } from "./misc_pb.js";
import { Account } from "../caip/account_pb.js";

/**
 * @generated from message printrfi.wingman.SolanaPrintFromEVMRequest
 */
export class SolanaPrintFromEVMRequest extends Message<SolanaPrintFromEVMRequest> {
  /**
   * @generated from field: printrfi.wingman.TelecoinParams telecoin_params = 1;
   */
  telecoinParams?: TelecoinParams;

  /**
   * @generated from field: printrfi.caip.Account payer = 2;
   */
  payer?: Account;

  constructor(data?: PartialMessage<SolanaPrintFromEVMRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaPrintFromEVMRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "telecoin_params", kind: "message", T: TelecoinParams },
    { no: 2, name: "payer", kind: "message", T: Account },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SolanaPrintFromEVMRequest {
    return new SolanaPrintFromEVMRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SolanaPrintFromEVMRequest {
    return new SolanaPrintFromEVMRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SolanaPrintFromEVMRequest {
    return new SolanaPrintFromEVMRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SolanaPrintFromEVMRequest | PlainMessage<SolanaPrintFromEVMRequest> | undefined, b: SolanaPrintFromEVMRequest | PlainMessage<SolanaPrintFromEVMRequest> | undefined): boolean {
    return proto3.util.equals(SolanaPrintFromEVMRequest, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.SolanaPrintFromEVMResponse
 */
export class SolanaPrintFromEVMResponse extends Message<SolanaPrintFromEVMResponse> {
  /**
   * Information about the telecoin on the destination chain.
   *
   * @generated from field: printrfi.wingman.TelecoinInstance on_destination = 1;
   */
  onDestination?: TelecoinInstance;

  /**
   * Information about what to expect from the tx.
   *
   * @generated from field: printrfi.wingman.TxInfo tx_info = 2;
   */
  txInfo?: TxInfo;

  /**
   * @generated from field: printrfi.wingman.EvmTx tx = 3;
   */
  tx?: EvmTx;

  constructor(data?: PartialMessage<SolanaPrintFromEVMResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaPrintFromEVMResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "on_destination", kind: "message", T: TelecoinInstance },
    { no: 2, name: "tx_info", kind: "message", T: TxInfo },
    { no: 3, name: "tx", kind: "message", T: EvmTx },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SolanaPrintFromEVMResponse {
    return new SolanaPrintFromEVMResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SolanaPrintFromEVMResponse {
    return new SolanaPrintFromEVMResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SolanaPrintFromEVMResponse {
    return new SolanaPrintFromEVMResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SolanaPrintFromEVMResponse | PlainMessage<SolanaPrintFromEVMResponse> | undefined, b: SolanaPrintFromEVMResponse | PlainMessage<SolanaPrintFromEVMResponse> | undefined): boolean {
    return proto3.util.equals(SolanaPrintFromEVMResponse, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.SolanaQuotePrintFromEVMResponse
 */
export class SolanaQuotePrintFromEVMResponse extends Message<SolanaQuotePrintFromEVMResponse> {
  /**
   * Information about the telecoin on the destination chain.
   *
   * @generated from field: printrfi.wingman.TelecoinInstance on_destination = 1;
   */
  onDestination?: TelecoinInstance;

  /**
   * Information about what to expect from the tx.
   *
   * @generated from field: printrfi.wingman.TxInfo tx_info = 2;
   */
  txInfo?: TxInfo;

  /**
   * @generated from field: printrfi.wingman.QuotedEvmTx tx = 3;
   */
  tx?: QuotedEvmTx;

  constructor(data?: PartialMessage<SolanaQuotePrintFromEVMResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaQuotePrintFromEVMResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "on_destination", kind: "message", T: TelecoinInstance },
    { no: 2, name: "tx_info", kind: "message", T: TxInfo },
    { no: 3, name: "tx", kind: "message", T: QuotedEvmTx },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SolanaQuotePrintFromEVMResponse {
    return new SolanaQuotePrintFromEVMResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SolanaQuotePrintFromEVMResponse {
    return new SolanaQuotePrintFromEVMResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SolanaQuotePrintFromEVMResponse {
    return new SolanaQuotePrintFromEVMResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SolanaQuotePrintFromEVMResponse | PlainMessage<SolanaQuotePrintFromEVMResponse> | undefined, b: SolanaQuotePrintFromEVMResponse | PlainMessage<SolanaQuotePrintFromEVMResponse> | undefined): boolean {
    return proto3.util.equals(SolanaQuotePrintFromEVMResponse, a, b);
  }
}

