// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file wingman/solana_has_associated_token_account.proto (package printrfi.wingman, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Base58Pubkey } from "./misc_pb.js";

/**
 * @generated from message printrfi.wingman.SolanaHasAssociatedTokenAccountRequest
 */
export class SolanaHasAssociatedTokenAccountRequest extends Message<SolanaHasAssociatedTokenAccountRequest> {
  /**
   * The Printr token ID as hex string.
   *
   * Required.
   *
   * @generated from field: string printr_token_id = 1;
   */
  printrTokenId = "";

  /**
   * What's the seed address of the user on Solana.
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey wallet = 2;
   */
  wallet?: Base58Pubkey;

  constructor(data?: PartialMessage<SolanaHasAssociatedTokenAccountRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaHasAssociatedTokenAccountRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "printr_token_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "wallet", kind: "message", T: Base58Pubkey },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): SolanaHasAssociatedTokenAccountRequest {
    return new SolanaHasAssociatedTokenAccountRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): SolanaHasAssociatedTokenAccountRequest {
    return new SolanaHasAssociatedTokenAccountRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): SolanaHasAssociatedTokenAccountRequest {
    return new SolanaHasAssociatedTokenAccountRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a:
      | SolanaHasAssociatedTokenAccountRequest
      | PlainMessage<SolanaHasAssociatedTokenAccountRequest>
      | undefined,
    b:
      | SolanaHasAssociatedTokenAccountRequest
      | PlainMessage<SolanaHasAssociatedTokenAccountRequest>
      | undefined,
  ): boolean {
    return proto3.util.equals(SolanaHasAssociatedTokenAccountRequest, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.SolanaHasAssociatedTokenAccountResponse
 */
export class SolanaHasAssociatedTokenAccountResponse extends Message<SolanaHasAssociatedTokenAccountResponse> {
  /**
   * Whether the user has an associated token account for the given Printr token.
   *
   * @generated from field: bool has_associated_token_account = 1;
   */
  hasAssociatedTokenAccount = false;

  constructor(data?: PartialMessage<SolanaHasAssociatedTokenAccountResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaHasAssociatedTokenAccountResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "has_associated_token_account", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): SolanaHasAssociatedTokenAccountResponse {
    return new SolanaHasAssociatedTokenAccountResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): SolanaHasAssociatedTokenAccountResponse {
    return new SolanaHasAssociatedTokenAccountResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): SolanaHasAssociatedTokenAccountResponse {
    return new SolanaHasAssociatedTokenAccountResponse().fromJsonString(jsonString, options);
  }

  static equals(
    a:
      | SolanaHasAssociatedTokenAccountResponse
      | PlainMessage<SolanaHasAssociatedTokenAccountResponse>
      | undefined,
    b:
      | SolanaHasAssociatedTokenAccountResponse
      | PlainMessage<SolanaHasAssociatedTokenAccountResponse>
      | undefined,
  ): boolean {
    return proto3.util.equals(SolanaHasAssociatedTokenAccountResponse, a, b);
  }
}
