// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file wingman/solana_xchain_buy_on_solana.proto (package printrfi.wingman, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Account } from "../caip/account_pb.js";
import { AssetAmount, Base58Pubkey, PrintrProtocolVersion, TokenAmount } from "./misc_pb.js";

/**
 * @generated from message printrfi.wingman.SolanaXchainBuyOnSolanaRequest
 */
export class SolanaXchainBuyOnSolanaRequest extends Message<SolanaXchainBuyOnSolanaRequest> {
  /**
   * The Printr interchain token ID as hex string.
   *
   * Required.
   *
   * @generated from field: string printr_token_id = 1;
   */
  printrTokenId = "";

  /**
   * The address of the spender on EVM.
   *
   * Required.
   *
   * @generated from field: printrfi.caip.Account spender = 3;
   */
  spender?: Account;

  /**
   * User's recipient address on the destination Solana chain.
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey recipient = 4;
   */
  recipient?: Base58Pubkey;

  /**
   * / The Printr protocol version associated with the token.
   *
   * @generated from field: printrfi.wingman.PrintrProtocolVersion token_protocol_version = 5;
   */
  tokenProtocolVersion?: PrintrProtocolVersion;

  /**
   * The asset and amount to spend on the source EVM chain.
   * The asset CAIP-10 identifies the token (e.g. native ETH or USDC).
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.AssetAmount spend_on_source = 6;
   */
  spendOnSource?: AssetAmount;

  constructor(data?: PartialMessage<SolanaXchainBuyOnSolanaRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaXchainBuyOnSolanaRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "printr_token_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "spender", kind: "message", T: Account },
    { no: 4, name: "recipient", kind: "message", T: Base58Pubkey },
    { no: 5, name: "token_protocol_version", kind: "message", T: PrintrProtocolVersion },
    { no: 6, name: "spend_on_source", kind: "message", T: AssetAmount },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): SolanaXchainBuyOnSolanaRequest {
    return new SolanaXchainBuyOnSolanaRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): SolanaXchainBuyOnSolanaRequest {
    return new SolanaXchainBuyOnSolanaRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): SolanaXchainBuyOnSolanaRequest {
    return new SolanaXchainBuyOnSolanaRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a: SolanaXchainBuyOnSolanaRequest | PlainMessage<SolanaXchainBuyOnSolanaRequest> | undefined,
    b: SolanaXchainBuyOnSolanaRequest | PlainMessage<SolanaXchainBuyOnSolanaRequest> | undefined,
  ): boolean {
    return proto3.util.equals(SolanaXchainBuyOnSolanaRequest, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.SolanaXchainBuyOnSolanaResponse
 */
export class SolanaXchainBuyOnSolanaResponse extends Message<SolanaXchainBuyOnSolanaResponse> {
  /**
   * Hex encoded (prefixed) EVM calldata to submit on the EVM chain.
   *
   * @generated from field: string hex_evm_calldata = 1;
   */
  hexEvmCalldata = "";

  /**
   * The `to` address when submitting the transaction on EVM.
   *
   * @generated from field: string evm_to = 2;
   */
  evmTo = "";

  /**
   * The `value` field of the transaction on EVM.
   *
   * @generated from field: string evm_value = 3;
   */
  evmValue = "";

  /**
   * How much telecoin should the user expect to receive on the destination Solana chain.
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.TokenAmount destination_telecoin_out = 4;
   */
  destinationTelecoinOut?: TokenAmount;

  /**
   * How much will the user spend on xchain fee.
   *
   * @generated from field: printrfi.wingman.TokenAmount xchain_fee_cost = 5;
   */
  xchainFeeCost?: TokenAmount;

  /**
   * How much will the user spend on the tx.
   *
   * @generated from field: printrfi.wingman.TokenAmount source_gas_cost = 6;
   */
  sourceGasCost?: TokenAmount;

  /**
   * Set the gas limit to this value when submitting the transaction on EVM.
   *
   * @generated from field: uint64 evm_gas_limit = 7;
   */
  evmGasLimit = protoInt64.zero;

  /**
   * Hex encoded "0x"-prefixed deBridge order ID for tracking the cross-chain transaction.
   *
   * Only relevant if this xchain spend is done via deBridge.
   *
   * @generated from field: string debridge_order_id = 8;
   */
  debridgeOrderId = "";

  constructor(data?: PartialMessage<SolanaXchainBuyOnSolanaResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaXchainBuyOnSolanaResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "hex_evm_calldata", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "evm_to", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "evm_value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "destination_telecoin_out", kind: "message", T: TokenAmount },
    { no: 5, name: "xchain_fee_cost", kind: "message", T: TokenAmount },
    { no: 6, name: "source_gas_cost", kind: "message", T: TokenAmount },
    { no: 7, name: "evm_gas_limit", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 8, name: "debridge_order_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): SolanaXchainBuyOnSolanaResponse {
    return new SolanaXchainBuyOnSolanaResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): SolanaXchainBuyOnSolanaResponse {
    return new SolanaXchainBuyOnSolanaResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): SolanaXchainBuyOnSolanaResponse {
    return new SolanaXchainBuyOnSolanaResponse().fromJsonString(jsonString, options);
  }

  static equals(
    a: SolanaXchainBuyOnSolanaResponse | PlainMessage<SolanaXchainBuyOnSolanaResponse> | undefined,
    b: SolanaXchainBuyOnSolanaResponse | PlainMessage<SolanaXchainBuyOnSolanaResponse> | undefined,
  ): boolean {
    return proto3.util.equals(SolanaXchainBuyOnSolanaResponse, a, b);
  }
}
