// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file wingman/solana_create_stake_position.proto (package printrfi.wingman, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Base58Pubkey, SolanaIx, TokenAmount } from "./misc_pb.js";

/**
 * @generated from enum printrfi.wingman.LockPeriodDays
 */
export enum LockPeriodDays {
  /**
   * @generated from enum value: LOCK_PERIOD_DAYS_SEVEN = 0;
   */
  SEVEN = 0,

  /**
   * @generated from enum value: LOCK_PERIOD_DAYS_FOURTEEN = 1;
   */
  FOURTEEN = 1,

  /**
   * @generated from enum value: LOCK_PERIOD_DAYS_THIRTY = 2;
   */
  THIRTY = 2,

  /**
   * @generated from enum value: LOCK_PERIOD_DAYS_SIXTY = 3;
   */
  SIXTY = 3,

  /**
   * @generated from enum value: LOCK_PERIOD_DAYS_NINETY = 4;
   */
  NINETY = 4,

  /**
   * @generated from enum value: LOCK_PERIOD_DAYS_ONE_HUNDRED_EIGHTY = 5;
   */
  ONE_HUNDRED_EIGHTY = 5,

  /**
   * @generated from enum value: LOCK_PERIOD_DAYS_TEN_SECONDS = 6;
   */
  TEN_SECONDS = 6,
}
// Retrieve enum metadata with: proto3.getEnumType(LockPeriodDays)
proto3.util.setEnumType(LockPeriodDays, "printrfi.wingman.LockPeriodDays", [
  { no: 0, name: "LOCK_PERIOD_DAYS_SEVEN" },
  { no: 1, name: "LOCK_PERIOD_DAYS_FOURTEEN" },
  { no: 2, name: "LOCK_PERIOD_DAYS_THIRTY" },
  { no: 3, name: "LOCK_PERIOD_DAYS_SIXTY" },
  { no: 4, name: "LOCK_PERIOD_DAYS_NINETY" },
  { no: 5, name: "LOCK_PERIOD_DAYS_ONE_HUNDRED_EIGHTY" },
  { no: 6, name: "LOCK_PERIOD_DAYS_TEN_SECONDS" },
]);

/**
 * @generated from message printrfi.wingman.SolanaCreateStakePositionRequest
 */
export class SolanaCreateStakePositionRequest extends Message<SolanaCreateStakePositionRequest> {
  /**
   * Who pays for the rent and becomes the position owner.
   * The tx that submits the returned ixs must be signed by this account.
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey payer = 1;
   */
  payer?: Base58Pubkey;

  /**
   * The Printr token ID as hex string.
   *
   * Required.
   *
   * @generated from field: string printr_token_id = 2;
   */
  printrTokenId = "";

  /**
   * Allows multiple positions per user.
   *
   * Required.
   *
   * @generated from field: uint32 position_nonce = 3;
   */
  positionNonce = 0;

  /**
   * Amount of telecoin to lock.
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.TokenAmount to_stake = 4;
   */
  toStake?: TokenAmount;

  /**
   * Lock period for the staked telecoin.
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.LockPeriodDays lock_period = 5;
   */
  lockPeriod = LockPeriodDays.SEVEN;

  constructor(data?: PartialMessage<SolanaCreateStakePositionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaCreateStakePositionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "payer", kind: "message", T: Base58Pubkey },
    { no: 2, name: "printr_token_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "position_nonce", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "to_stake", kind: "message", T: TokenAmount },
    { no: 5, name: "lock_period", kind: "enum", T: proto3.getEnumType(LockPeriodDays) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SolanaCreateStakePositionRequest {
    return new SolanaCreateStakePositionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SolanaCreateStakePositionRequest {
    return new SolanaCreateStakePositionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SolanaCreateStakePositionRequest {
    return new SolanaCreateStakePositionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SolanaCreateStakePositionRequest | PlainMessage<SolanaCreateStakePositionRequest> | undefined, b: SolanaCreateStakePositionRequest | PlainMessage<SolanaCreateStakePositionRequest> | undefined): boolean {
    return proto3.util.equals(SolanaCreateStakePositionRequest, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.SolanaCreateStakePositionResponse
 */
export class SolanaCreateStakePositionResponse extends Message<SolanaCreateStakePositionResponse> {
  /**
   * The new stake position PDA address.
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey stake_position = 1;
   */
  stakePosition?: Base58Pubkey;

  /**
   * The ixs with which to build a tx.
   *
   * Required.
   *
   * @generated from field: repeated printrfi.wingman.SolanaIx ixs = 2;
   */
  ixs: SolanaIx[] = [];

  /**
   * Use this lookup table to minimize the tx size.
   *
   * Optional.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey lookup_table = 3;
   */
  lookupTable?: Base58Pubkey;

  constructor(data?: PartialMessage<SolanaCreateStakePositionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaCreateStakePositionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "stake_position", kind: "message", T: Base58Pubkey },
    { no: 2, name: "ixs", kind: "message", T: SolanaIx, repeated: true },
    { no: 3, name: "lookup_table", kind: "message", T: Base58Pubkey },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SolanaCreateStakePositionResponse {
    return new SolanaCreateStakePositionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SolanaCreateStakePositionResponse {
    return new SolanaCreateStakePositionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SolanaCreateStakePositionResponse {
    return new SolanaCreateStakePositionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SolanaCreateStakePositionResponse | PlainMessage<SolanaCreateStakePositionResponse> | undefined, b: SolanaCreateStakePositionResponse | PlainMessage<SolanaCreateStakePositionResponse> | undefined): boolean {
    return proto3.util.equals(SolanaCreateStakePositionResponse, a, b);
  }
}

