// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file wingman/solana_curve_progress.proto (package printrfi.wingman, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { TokenAmount } from "./misc_pb.js";

/**
 * @generated from message printrfi.wingman.SolanaCurveProgressRequest
 */
export class SolanaCurveProgressRequest extends Message<SolanaCurveProgressRequest> {
  /**
   * The Printr token ID as hex string.
   *
   * Required.
   *
   * @generated from field: string printr_token_id = 1;
   */
  printrTokenId = "";

  constructor(data?: PartialMessage<SolanaCurveProgressRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaCurveProgressRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "printr_token_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SolanaCurveProgressRequest {
    return new SolanaCurveProgressRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SolanaCurveProgressRequest {
    return new SolanaCurveProgressRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SolanaCurveProgressRequest {
    return new SolanaCurveProgressRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SolanaCurveProgressRequest | PlainMessage<SolanaCurveProgressRequest> | undefined, b: SolanaCurveProgressRequest | PlainMessage<SolanaCurveProgressRequest> | undefined): boolean {
    return proto3.util.equals(SolanaCurveProgressRequest, a, b);
  }
}

/**
 * All progress values are in the range [0, 1] where 0 means no progress and 1 means bonding curve
 * threshold has been reached.
 *
 * Note that while 1 is the maximum value for progress it does not mean that the curve is fully
 * graduated.
 * It could be waiting for graduation.
 *
 * @generated from message printrfi.wingman.SolanaCurveProgressResponse
 */
export class SolanaCurveProgressResponse extends Message<SolanaCurveProgressResponse> {
  /**
   * current supply / graduation supply
   *
   * @generated from field: float in_terms_of_telecoin_supply = 1;
   */
  inTermsOfTelecoinSupply = 0;

  /**
   * current reserve / graduation reserve
   *
   * @generated from field: float in_terms_of_quote_collected = 2;
   */
  inTermsOfQuoteCollected = 0;

  /**
   * current price * current supply / (graduation price * graduation supply)
   *
   * @generated from field: float in_terms_of_quote_market_cap = 3;
   */
  inTermsOfQuoteMarketCap = 0;

  /**
   * current price / graduation price
   *
   * @generated from field: float in_terms_of_current_price = 4;
   */
  inTermsOfCurrentPrice = 0;

  /**
   * How much quote token is collected on the bonding curve.
   *
   * @generated from field: printrfi.wingman.TokenAmount current_quote_reserve = 5;
   */
  currentQuoteReserve?: TokenAmount;

  /**
   * How much quote token is needed to graduate the bonding curve.
   *
   * @generated from field: printrfi.wingman.TokenAmount graduation_quote_reserve = 6;
   */
  graduationQuoteReserve?: TokenAmount;

  /**
   * How much telecoin was minted on creation of the curve.
   *
   * @generated from field: printrfi.wingman.TokenAmount total_telecoin_supply_on_this_chain = 7;
   */
  totalTelecoinSupplyOnThisChain?: TokenAmount;

  /**
   * How much telecoin is currently circulating from this curve.
   *
   * @generated from field: printrfi.wingman.TokenAmount current_telecoin_supply_on_this_curve = 8;
   */
  currentTelecoinSupplyOnThisCurve?: TokenAmount;

  /**
   * How much telecoin will be circulating from this curve when it graduates.
   *
   * @generated from field: printrfi.wingman.TokenAmount graduation_telecoin_supply_on_this_curve = 9;
   */
  graduationTelecoinSupplyOnThisCurve?: TokenAmount;

  constructor(data?: PartialMessage<SolanaCurveProgressResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaCurveProgressResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "in_terms_of_telecoin_supply", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 2, name: "in_terms_of_quote_collected", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 3, name: "in_terms_of_quote_market_cap", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 4, name: "in_terms_of_current_price", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 5, name: "current_quote_reserve", kind: "message", T: TokenAmount },
    { no: 6, name: "graduation_quote_reserve", kind: "message", T: TokenAmount },
    { no: 7, name: "total_telecoin_supply_on_this_chain", kind: "message", T: TokenAmount },
    { no: 8, name: "current_telecoin_supply_on_this_curve", kind: "message", T: TokenAmount },
    { no: 9, name: "graduation_telecoin_supply_on_this_curve", kind: "message", T: TokenAmount },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SolanaCurveProgressResponse {
    return new SolanaCurveProgressResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SolanaCurveProgressResponse {
    return new SolanaCurveProgressResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SolanaCurveProgressResponse {
    return new SolanaCurveProgressResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SolanaCurveProgressResponse | PlainMessage<SolanaCurveProgressResponse> | undefined, b: SolanaCurveProgressResponse | PlainMessage<SolanaCurveProgressResponse> | undefined): boolean {
    return proto3.util.equals(SolanaCurveProgressResponse, a, b);
  }
}

