// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file wingman/solana_create_curve.proto (package printrfi.wingman, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Base58Pubkey, SolanaIx, TelecoinParams, TokenAmount } from "./misc_pb.js";

/**
 * @generated from message printrfi.wingman.SolanaCreateCurveRequest
 */
export class SolanaCreateCurveRequest extends Message<SolanaCreateCurveRequest> {
  /**
   * Who pays for the rent, typically the user's pubkey.
   * The tx that submits the returned ixs must be signed by this account.
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey payer = 1;
   */
  payer?: Base58Pubkey;

  /**
   * Required.
   *
   * @generated from field: printrfi.wingman.TelecoinParams token_params = 2;
   */
  tokenParams?: TelecoinParams;

  /**
   * If not provided then we use the payer's associated token account
   *
   * Optional.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey payer_quote_token_account = 3;
   */
  payerQuoteTokenAccount?: Base58Pubkey;

  /**
   * If set to non-zero then the calldata will include a transfer of native $SOL to a configured
   * wallet owned by Printr.
   *
   * @generated from field: uint64 printr_fee_lamports = 4;
   */
  printrFeeLamports = protoInt64.zero;

  constructor(data?: PartialMessage<SolanaCreateCurveRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaCreateCurveRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "payer", kind: "message", T: Base58Pubkey },
    { no: 2, name: "token_params", kind: "message", T: TelecoinParams },
    { no: 3, name: "payer_quote_token_account", kind: "message", T: Base58Pubkey },
    { no: 4, name: "printr_fee_lamports", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): SolanaCreateCurveRequest {
    return new SolanaCreateCurveRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): SolanaCreateCurveRequest {
    return new SolanaCreateCurveRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): SolanaCreateCurveRequest {
    return new SolanaCreateCurveRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a: SolanaCreateCurveRequest | PlainMessage<SolanaCreateCurveRequest> | undefined,
    b: SolanaCreateCurveRequest | PlainMessage<SolanaCreateCurveRequest> | undefined,
  ): boolean {
    return proto3.util.equals(SolanaCreateCurveRequest, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.SolanaCreateCurveResponse
 */
export class SolanaCreateCurveResponse extends Message<SolanaCreateCurveResponse> {
  /**
   * The token program 2022 mint account
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey telecoin_mint = 1;
   */
  telecoinMint?: Base58Pubkey;

  /**
   * The Printr interchain token ID as hex string.
   *
   * Required.
   *
   * @generated from field: string printr_token_id = 2;
   */
  printrTokenId = "";

  /**
   * The ixs with which to build a tx
   *
   * Required.
   *
   * @generated from field: repeated printrfi.wingman.SolanaIx ixs = 3;
   */
  ixs: SolanaIx[] = [];

  /**
   * Use this lookup table to minimize the tx size
   *
   * Optional.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey lookup_table = 4;
   */
  lookupTable?: Base58Pubkey;

  /**
   * The cost of the route in lamports.
   *
   * @generated from field: printrfi.wingman.DeploymentCost deployment_cost = 5;
   */
  deploymentCost?: DeploymentCost;

  /**
   * Meteora's DBC pool account.
   *
   * @generated from field: printrfi.wingman.Base58Pubkey bonding_curve = 6;
   */
  bondingCurve?: Base58Pubkey;

  /**
   * The amount of quote token that must be collected on the bonding curve before it can be
   * graduated to DAMMv2.
   *
   * @generated from field: uint64 graduation_threshold_quote = 7;
   */
  graduationThresholdQuote = protoInt64.zero;

  /**
   * Formatted initial price in quote token for display purposes.
   * Ie. "how much quote token to get 1 telecoin token".
   *
   * @generated from field: string initial_price_display = 8;
   */
  initialPriceDisplay = "";

  constructor(data?: PartialMessage<SolanaCreateCurveResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.SolanaCreateCurveResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "telecoin_mint", kind: "message", T: Base58Pubkey },
    { no: 2, name: "printr_token_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "ixs", kind: "message", T: SolanaIx, repeated: true },
    { no: 4, name: "lookup_table", kind: "message", T: Base58Pubkey },
    { no: 5, name: "deployment_cost", kind: "message", T: DeploymentCost },
    { no: 6, name: "bonding_curve", kind: "message", T: Base58Pubkey },
    { no: 7, name: "graduation_threshold_quote", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 8, name: "initial_price_display", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): SolanaCreateCurveResponse {
    return new SolanaCreateCurveResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): SolanaCreateCurveResponse {
    return new SolanaCreateCurveResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): SolanaCreateCurveResponse {
    return new SolanaCreateCurveResponse().fromJsonString(jsonString, options);
  }

  static equals(
    a: SolanaCreateCurveResponse | PlainMessage<SolanaCreateCurveResponse> | undefined,
    b: SolanaCreateCurveResponse | PlainMessage<SolanaCreateCurveResponse> | undefined,
  ): boolean {
    return proto3.util.equals(SolanaCreateCurveResponse, a, b);
  }
}

/**
 * Gathers information about the expected (conservative) cost for a deployment on a chain.
 *
 * @generated from message printrfi.wingman.DeploymentCost
 */
export class DeploymentCost extends Message<DeploymentCost> {
  /**
   * Lamports spent on gas.
   *
   * @generated from field: printrfi.wingman.TokenAmount gas = 1;
   */
  gas?: TokenAmount;

  /**
   * Lamports spent on rent.
   *
   * @generated from field: printrfi.wingman.TokenAmount rent = 2;
   */
  rent?: TokenAmount;

  /**
   * How much of the quote token will be spent on the initial spend.
   *
   * @generated from field: printrfi.wingman.TokenAmount initial_spending_quote = 3;
   */
  initialSpendingQuote?: TokenAmount;

  constructor(data?: PartialMessage<DeploymentCost>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.DeploymentCost";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "gas", kind: "message", T: TokenAmount },
    { no: 2, name: "rent", kind: "message", T: TokenAmount },
    { no: 3, name: "initial_spending_quote", kind: "message", T: TokenAmount },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeploymentCost {
    return new DeploymentCost().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeploymentCost {
    return new DeploymentCost().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeploymentCost {
    return new DeploymentCost().fromJsonString(jsonString, options);
  }

  static equals(
    a: DeploymentCost | PlainMessage<DeploymentCost> | undefined,
    b: DeploymentCost | PlainMessage<DeploymentCost> | undefined,
  ): boolean {
    return proto3.util.equals(DeploymentCost, a, b);
  }
}
