// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file wingman/wingman_outbound.proto (package printrfi.wingman, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EventBuybackAndBurnRequest, EventDebridgeOrderExecutedRequest, EventProjectedStakingRewardsRequest, EventStakePositionCreatedRequest, EventStakingRefreshedRequest, EventStakingRewardsClaimedRequest, EventTeleportInRequest, EventTeleportOutRequest, EventTokenContractDeployedRequest, EventTokenGraduatedRequest } from "./wingman_outbound_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service printrfi.wingman.WingmanOutbound
 */
export const WingmanOutbound = {
  typeName: "printrfi.wingman.WingmanOutbound",
  methods: {
    /**
     * @generated from rpc printrfi.wingman.WingmanOutbound.EventTokenContractDeployed
     */
    eventTokenContractDeployed: {
      name: "EventTokenContractDeployed",
      I: EventTokenContractDeployedRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.wingman.WingmanOutbound.EventTokenGraduated
     */
    eventTokenGraduated: {
      name: "EventTokenGraduated",
      I: EventTokenGraduatedRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.wingman.WingmanOutbound.EventTeleportIn
     */
    eventTeleportIn: {
      name: "EventTeleportIn",
      I: EventTeleportInRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.wingman.WingmanOutbound.EventTeleportOut
     */
    eventTeleportOut: {
      name: "EventTeleportOut",
      I: EventTeleportOutRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.wingman.WingmanOutbound.EventDebridgeOrderExecuted
     */
    eventDebridgeOrderExecuted: {
      name: "EventDebridgeOrderExecuted",
      I: EventDebridgeOrderExecutedRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.wingman.WingmanOutbound.EventStakePositionCreated
     */
    eventStakePositionCreated: {
      name: "EventStakePositionCreated",
      I: EventStakePositionCreatedRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.wingman.WingmanOutbound.EventStakingRewardsClaimed
     */
    eventStakingRewardsClaimed: {
      name: "EventStakingRewardsClaimed",
      I: EventStakingRewardsClaimedRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.wingman.WingmanOutbound.EventStakingRefreshed
     */
    eventStakingRefreshed: {
      name: "EventStakingRefreshed",
      I: EventStakingRefreshedRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.wingman.WingmanOutbound.EventProjectedStakingRewards
     */
    eventProjectedStakingRewards: {
      name: "EventProjectedStakingRewards",
      I: EventProjectedStakingRewardsRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc printrfi.wingman.WingmanOutbound.EventBuybackAndBurn
     */
    eventBuybackAndBurn: {
      name: "EventBuybackAndBurn",
      I: EventBuybackAndBurnRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

