// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file wingman/wingman_outbound.proto (package printrfi.wingman, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";
import { Account } from "../caip/account_pb.js";
import { Accumulator, PrintrProtocolVersion, TokenAmount } from "./misc_pb.js";
import { LockPeriodDays } from "./solana_create_stake_position_pb.js";

/**
 * Follows the existing schema for EVM, even though there's no "contract" concept in Solana for tokens.
 *
 * @generated from message printrfi.wingman.EventTokenContractDeployedRequest
 */
export class EventTokenContractDeployedRequest extends Message<EventTokenContractDeployedRequest> {
  /**
   * @generated from field: string telecoin_id = 1;
   */
  telecoinId = "";

  /**
   * @generated from field: string chain_id = 2;
   */
  chainId = "";

  /**
   * @generated from field: string creator_address = 3;
   */
  creatorAddress = "";

  /**
   * @generated from field: string telecoin_mint_address = 4;
   */
  telecoinMintAddress = "";

  /**
   * @generated from field: string transaction_id = 5;
   */
  transactionId = "";

  /**
   * @generated from field: string block_number = 6;
   */
  blockNumber = "";

  /**
   * @generated from field: optional google.protobuf.Timestamp block_timestamp = 7;
   */
  blockTimestamp?: Timestamp;

  /**
   * @generated from field: string bonding_curve_address = 8;
   */
  bondingCurveAddress = "";

  /**
   * @generated from field: string amm_address = 9;
   */
  ammAddress = "";

  /**
   * As reported by the Solana program that launched the token.
   * Wingman expects this version to be sent in requests to generate calldata.
   *
   * @generated from field: printrfi.wingman.PrintrProtocolVersion protocol_version = 10;
   */
  protocolVersion?: PrintrProtocolVersion;

  constructor(data?: PartialMessage<EventTokenContractDeployedRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.EventTokenContractDeployedRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "telecoin_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "chain_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "creator_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "telecoin_mint_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "transaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "block_number", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "block_timestamp", kind: "message", T: Timestamp, opt: true },
    { no: 8, name: "bonding_curve_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "amm_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "protocol_version", kind: "message", T: PrintrProtocolVersion },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): EventTokenContractDeployedRequest {
    return new EventTokenContractDeployedRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): EventTokenContractDeployedRequest {
    return new EventTokenContractDeployedRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): EventTokenContractDeployedRequest {
    return new EventTokenContractDeployedRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a:
      | EventTokenContractDeployedRequest
      | PlainMessage<EventTokenContractDeployedRequest>
      | undefined,
    b:
      | EventTokenContractDeployedRequest
      | PlainMessage<EventTokenContractDeployedRequest>
      | undefined,
  ): boolean {
    return proto3.util.equals(EventTokenContractDeployedRequest, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.EventTokenGraduatedRequest
 */
export class EventTokenGraduatedRequest extends Message<EventTokenGraduatedRequest> {
  /**
   * @generated from field: string telecoin_id = 1;
   */
  telecoinId = "";

  /**
   * @generated from field: string chain_id = 2;
   */
  chainId = "";

  /**
   * @generated from field: string telecoin_mint_address = 3;
   */
  telecoinMintAddress = "";

  /**
   * @generated from field: string telecoin_amount = 4;
   */
  telecoinAmount = "";

  /**
   * @generated from field: string quote_amount = 5;
   */
  quoteAmount = "";

  /**
   * @generated from field: string transaction_id = 6;
   */
  transactionId = "";

  /**
   * @generated from field: string block_number = 7;
   */
  blockNumber = "";

  /**
   * @generated from field: optional google.protobuf.Timestamp block_timestamp = 8;
   */
  blockTimestamp?: Timestamp;

  constructor(data?: PartialMessage<EventTokenGraduatedRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.EventTokenGraduatedRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "telecoin_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "chain_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "telecoin_mint_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "telecoin_amount", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "quote_amount", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "transaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "block_number", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "block_timestamp", kind: "message", T: Timestamp, opt: true },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): EventTokenGraduatedRequest {
    return new EventTokenGraduatedRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): EventTokenGraduatedRequest {
    return new EventTokenGraduatedRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): EventTokenGraduatedRequest {
    return new EventTokenGraduatedRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a: EventTokenGraduatedRequest | PlainMessage<EventTokenGraduatedRequest> | undefined,
    b: EventTokenGraduatedRequest | PlainMessage<EventTokenGraduatedRequest> | undefined,
  ): boolean {
    return proto3.util.equals(EventTokenGraduatedRequest, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.EventTeleportOutRequest
 */
export class EventTeleportOutRequest extends Message<EventTeleportOutRequest> {
  /**
   * @generated from field: string telecoin_id = 1;
   */
  telecoinId = "";

  /**
   * @generated from field: printrfi.caip.Account peer = 2;
   */
  peer?: Account;

  /**
   * @generated from field: printrfi.caip.Account source_sender = 3;
   */
  sourceSender?: Account;

  /**
   * @generated from field: printrfi.caip.Account destination_recipient = 4;
   */
  destinationRecipient?: Account;

  /**
   * @generated from field: printrfi.wingman.TokenAmount teleporting = 5;
   */
  teleporting?: TokenAmount;

  /**
   * hex encoded without 0x prefix
   *
   * @generated from field: string guid = 6;
   */
  guid = "";

  /**
   * @generated from field: string transaction_id = 7;
   */
  transactionId = "";

  /**
   * @generated from field: string block_number = 8;
   */
  blockNumber = "";

  /**
   * @generated from field: optional google.protobuf.Timestamp block_timestamp = 9;
   */
  blockTimestamp?: Timestamp;

  constructor(data?: PartialMessage<EventTeleportOutRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.EventTeleportOutRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "telecoin_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "peer", kind: "message", T: Account },
    { no: 3, name: "source_sender", kind: "message", T: Account },
    { no: 4, name: "destination_recipient", kind: "message", T: Account },
    { no: 5, name: "teleporting", kind: "message", T: TokenAmount },
    { no: 6, name: "guid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "transaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "block_number", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "block_timestamp", kind: "message", T: Timestamp, opt: true },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): EventTeleportOutRequest {
    return new EventTeleportOutRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): EventTeleportOutRequest {
    return new EventTeleportOutRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): EventTeleportOutRequest {
    return new EventTeleportOutRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a: EventTeleportOutRequest | PlainMessage<EventTeleportOutRequest> | undefined,
    b: EventTeleportOutRequest | PlainMessage<EventTeleportOutRequest> | undefined,
  ): boolean {
    return proto3.util.equals(EventTeleportOutRequest, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.EventTeleportInRequest
 */
export class EventTeleportInRequest extends Message<EventTeleportInRequest> {
  /**
   * @generated from field: string telecoin_id = 1;
   */
  telecoinId = "";

  /**
   * @generated from field: printrfi.caip.Account peer = 2;
   */
  peer?: Account;

  /**
   * @generated from field: printrfi.caip.Account destination_recipient = 3;
   */
  destinationRecipient?: Account;

  /**
   * @generated from field: printrfi.wingman.TokenAmount teleported = 4;
   */
  teleported?: TokenAmount;

  /**
   * hex encoded without 0x prefix
   *
   * @generated from field: string guid = 5;
   */
  guid = "";

  /**
   * @generated from field: string transaction_id = 6;
   */
  transactionId = "";

  /**
   * @generated from field: string block_number = 7;
   */
  blockNumber = "";

  /**
   * @generated from field: optional google.protobuf.Timestamp block_timestamp = 8;
   */
  blockTimestamp?: Timestamp;

  constructor(data?: PartialMessage<EventTeleportInRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.EventTeleportInRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "telecoin_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "peer", kind: "message", T: Account },
    { no: 3, name: "destination_recipient", kind: "message", T: Account },
    { no: 4, name: "teleported", kind: "message", T: TokenAmount },
    { no: 5, name: "guid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "transaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "block_number", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "block_timestamp", kind: "message", T: Timestamp, opt: true },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): EventTeleportInRequest {
    return new EventTeleportInRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): EventTeleportInRequest {
    return new EventTeleportInRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): EventTeleportInRequest {
    return new EventTeleportInRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a: EventTeleportInRequest | PlainMessage<EventTeleportInRequest> | undefined,
    b: EventTeleportInRequest | PlainMessage<EventTeleportInRequest> | undefined,
  ): boolean {
    return proto3.util.equals(EventTeleportInRequest, a, b);
  }
}

/**
 * Tracks "useful" deBridge order executions.
 * Useful are those that touch telecoins.
 *
 * @generated from message printrfi.wingman.EventDebridgeOrderExecutedRequest
 */
export class EventDebridgeOrderExecutedRequest extends Message<EventDebridgeOrderExecutedRequest> {
  /**
   * Hex encoded "0x"-prefixed deBridge order ID for tracking the cross-chain transaction.
   *
   * @generated from field: string debridge_order_id = 1;
   */
  debridgeOrderId = "";

  /**
   * @generated from field: string transaction_id = 2;
   */
  transactionId = "";

  /**
   * @generated from field: string block_number = 3;
   */
  blockNumber = "";

  /**
   * @generated from field: optional google.protobuf.Timestamp block_timestamp = 4;
   */
  blockTimestamp?: Timestamp;

  constructor(data?: PartialMessage<EventDebridgeOrderExecutedRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.EventDebridgeOrderExecutedRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "debridge_order_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "transaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "block_number", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "block_timestamp", kind: "message", T: Timestamp, opt: true },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): EventDebridgeOrderExecutedRequest {
    return new EventDebridgeOrderExecutedRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): EventDebridgeOrderExecutedRequest {
    return new EventDebridgeOrderExecutedRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): EventDebridgeOrderExecutedRequest {
    return new EventDebridgeOrderExecutedRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a:
      | EventDebridgeOrderExecutedRequest
      | PlainMessage<EventDebridgeOrderExecutedRequest>
      | undefined,
    b:
      | EventDebridgeOrderExecutedRequest
      | PlainMessage<EventDebridgeOrderExecutedRequest>
      | undefined,
  ): boolean {
    return proto3.util.equals(EventDebridgeOrderExecutedRequest, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.EventStakePositionCreatedRequest
 */
export class EventStakePositionCreatedRequest extends Message<EventStakePositionCreatedRequest> {
  /**
   * @generated from field: string telecoin_id = 1;
   */
  telecoinId = "";

  /**
   * @generated from field: string owner_address = 2;
   */
  ownerAddress = "";

  /**
   * @generated from field: uint32 position_nonce = 3;
   */
  positionNonce = 0;

  /**
   * @generated from field: printrfi.wingman.TokenAmount staked = 4;
   */
  staked?: TokenAmount;

  /**
   * @generated from field: printrfi.wingman.LockPeriodDays lock_period = 5;
   */
  lockPeriod = LockPeriodDays.SEVEN;

  /**
   * @generated from field: string transaction_id = 6;
   */
  transactionId = "";

  /**
   * @generated from field: string block_number = 7;
   */
  blockNumber = "";

  /**
   * @generated from field: optional google.protobuf.Timestamp block_timestamp = 8;
   */
  blockTimestamp?: Timestamp;

  /**
   * Unix timestamp from the Solana clock when staking was created.
   *
   * @generated from field: int64 staked_at_clock_timestamp = 9;
   */
  stakedAtClockTimestamp = protoInt64.zero;

  /**
   * @generated from field: printrfi.wingman.Accumulator quote_token_accumulator = 10;
   */
  quoteTokenAccumulator?: Accumulator;

  /**
   * @generated from field: printrfi.wingman.Accumulator telecoin_accumulator = 11;
   */
  telecoinAccumulator?: Accumulator;

  /**
   * @generated from field: string telecoin_mint_address = 12;
   */
  telecoinMintAddress = "";

  /**
   * The on-chain staking position PDA.
   *
   * @generated from field: string position_address = 13;
   */
  positionAddress = "";

  constructor(data?: PartialMessage<EventStakePositionCreatedRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.EventStakePositionCreatedRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "telecoin_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "owner_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "position_nonce", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "staked", kind: "message", T: TokenAmount },
    { no: 5, name: "lock_period", kind: "enum", T: proto3.getEnumType(LockPeriodDays) },
    { no: 6, name: "transaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "block_number", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "block_timestamp", kind: "message", T: Timestamp, opt: true },
    { no: 9, name: "staked_at_clock_timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 10, name: "quote_token_accumulator", kind: "message", T: Accumulator },
    { no: 11, name: "telecoin_accumulator", kind: "message", T: Accumulator },
    { no: 12, name: "telecoin_mint_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "position_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): EventStakePositionCreatedRequest {
    return new EventStakePositionCreatedRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): EventStakePositionCreatedRequest {
    return new EventStakePositionCreatedRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): EventStakePositionCreatedRequest {
    return new EventStakePositionCreatedRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a:
      | EventStakePositionCreatedRequest
      | PlainMessage<EventStakePositionCreatedRequest>
      | undefined,
    b:
      | EventStakePositionCreatedRequest
      | PlainMessage<EventStakePositionCreatedRequest>
      | undefined,
  ): boolean {
    return proto3.util.equals(EventStakePositionCreatedRequest, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.EventStakingRewardsClaimedRequest
 */
export class EventStakingRewardsClaimedRequest extends Message<EventStakingRewardsClaimedRequest> {
  /**
   * @generated from field: string owner_address = 1;
   */
  ownerAddress = "";

  /**
   * @generated from field: string telecoin_mint_address = 2;
   */
  telecoinMintAddress = "";

  /**
   * @generated from field: uint32 position_nonce = 3;
   */
  positionNonce = 0;

  /**
   * @generated from field: printrfi.wingman.TokenAmount quote_rewards = 4;
   */
  quoteRewards?: TokenAmount;

  /**
   * @generated from field: printrfi.wingman.TokenAmount telecoin_rewards = 5;
   */
  telecoinRewards?: TokenAmount;

  /**
   * @generated from field: bool was_position_closed = 6;
   */
  wasPositionClosed = false;

  /**
   * @generated from field: printrfi.wingman.TokenAmount returned_stake = 7;
   */
  returnedStake?: TokenAmount;

  /**
   * @generated from field: string transaction_id = 8;
   */
  transactionId = "";

  /**
   * @generated from field: string block_number = 9;
   */
  blockNumber = "";

  /**
   * @generated from field: optional google.protobuf.Timestamp block_timestamp = 10;
   */
  blockTimestamp?: Timestamp;

  /**
   * @generated from field: printrfi.wingman.Accumulator quote_token_accumulator = 11;
   */
  quoteTokenAccumulator?: Accumulator;

  /**
   * @generated from field: printrfi.wingman.Accumulator telecoin_accumulator = 12;
   */
  telecoinAccumulator?: Accumulator;

  /**
   * The on-chain staking position PDA.
   *
   * @generated from field: string position_address = 13;
   */
  positionAddress = "";

  /**
   * @generated from field: string telecoin_id = 14;
   */
  telecoinId = "";

  constructor(data?: PartialMessage<EventStakingRewardsClaimedRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.EventStakingRewardsClaimedRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "owner_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "telecoin_mint_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "position_nonce", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "quote_rewards", kind: "message", T: TokenAmount },
    { no: 5, name: "telecoin_rewards", kind: "message", T: TokenAmount },
    { no: 6, name: "was_position_closed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "returned_stake", kind: "message", T: TokenAmount },
    { no: 8, name: "transaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "block_number", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "block_timestamp", kind: "message", T: Timestamp, opt: true },
    { no: 11, name: "quote_token_accumulator", kind: "message", T: Accumulator },
    { no: 12, name: "telecoin_accumulator", kind: "message", T: Accumulator },
    { no: 13, name: "position_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "telecoin_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): EventStakingRewardsClaimedRequest {
    return new EventStakingRewardsClaimedRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): EventStakingRewardsClaimedRequest {
    return new EventStakingRewardsClaimedRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): EventStakingRewardsClaimedRequest {
    return new EventStakingRewardsClaimedRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a:
      | EventStakingRewardsClaimedRequest
      | PlainMessage<EventStakingRewardsClaimedRequest>
      | undefined,
    b:
      | EventStakingRewardsClaimedRequest
      | PlainMessage<EventStakingRewardsClaimedRequest>
      | undefined,
  ): boolean {
    return proto3.util.equals(EventStakingRewardsClaimedRequest, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.EventStakingRefreshedRequest
 */
export class EventStakingRefreshedRequest extends Message<EventStakingRefreshedRequest> {
  /**
   * @generated from field: string telecoin_id = 1;
   */
  telecoinId = "";

  /**
   * @generated from field: printrfi.wingman.TokenAmount quote_rewards = 2;
   */
  quoteRewards?: TokenAmount;

  /**
   * @generated from field: printrfi.wingman.TokenAmount protocol_quote_fees = 3;
   */
  protocolQuoteFees?: TokenAmount;

  /**
   * @generated from field: printrfi.wingman.TokenAmount telecoin_rewards = 4;
   */
  telecoinRewards?: TokenAmount;

  /**
   * @generated from field: printrfi.wingman.Accumulator quote_token_accumulator = 5;
   */
  quoteTokenAccumulator?: Accumulator;

  /**
   * @generated from field: printrfi.wingman.Accumulator telecoin_accumulator = 6;
   */
  telecoinAccumulator?: Accumulator;

  /**
   * @generated from field: string transaction_id = 7;
   */
  transactionId = "";

  /**
   * @generated from field: string block_number = 8;
   */
  blockNumber = "";

  /**
   * @generated from field: optional google.protobuf.Timestamp block_timestamp = 9;
   */
  blockTimestamp?: Timestamp;

  /**
   * @generated from field: string telecoin_mint_address = 10;
   */
  telecoinMintAddress = "";

  constructor(data?: PartialMessage<EventStakingRefreshedRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.EventStakingRefreshedRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "telecoin_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "quote_rewards", kind: "message", T: TokenAmount },
    { no: 3, name: "protocol_quote_fees", kind: "message", T: TokenAmount },
    { no: 4, name: "telecoin_rewards", kind: "message", T: TokenAmount },
    { no: 5, name: "quote_token_accumulator", kind: "message", T: Accumulator },
    { no: 6, name: "telecoin_accumulator", kind: "message", T: Accumulator },
    { no: 7, name: "transaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "block_number", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "block_timestamp", kind: "message", T: Timestamp, opt: true },
    { no: 10, name: "telecoin_mint_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): EventStakingRefreshedRequest {
    return new EventStakingRefreshedRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): EventStakingRefreshedRequest {
    return new EventStakingRefreshedRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): EventStakingRefreshedRequest {
    return new EventStakingRefreshedRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a: EventStakingRefreshedRequest | PlainMessage<EventStakingRefreshedRequest> | undefined,
    b: EventStakingRefreshedRequest | PlainMessage<EventStakingRefreshedRequest> | undefined,
  ): boolean {
    return proto3.util.equals(EventStakingRefreshedRequest, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.EventProjectedStakingRewardsRequest
 */
export class EventProjectedStakingRewardsRequest extends Message<EventProjectedStakingRewardsRequest> {
  /**
   * @generated from field: string telecoin_id = 1;
   */
  telecoinId = "";

  /**
   * @generated from field: printrfi.wingman.TokenAmount quote_rewards = 2;
   */
  quoteRewards?: TokenAmount;

  /**
   * @generated from field: printrfi.wingman.TokenAmount protocol_quote_fees = 3;
   */
  protocolQuoteFees?: TokenAmount;

  /**
   * @generated from field: printrfi.wingman.Accumulator quote_token_accumulator = 4;
   */
  quoteTokenAccumulator?: Accumulator;

  /**
   * @generated from field: printrfi.wingman.Accumulator telecoin_accumulator = 5;
   */
  telecoinAccumulator?: Accumulator;

  /**
   * @generated from field: string telecoin_mint_address = 6;
   */
  telecoinMintAddress = "";

  constructor(data?: PartialMessage<EventProjectedStakingRewardsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.EventProjectedStakingRewardsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "telecoin_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "quote_rewards", kind: "message", T: TokenAmount },
    { no: 3, name: "protocol_quote_fees", kind: "message", T: TokenAmount },
    { no: 4, name: "quote_token_accumulator", kind: "message", T: Accumulator },
    { no: 5, name: "telecoin_accumulator", kind: "message", T: Accumulator },
    { no: 6, name: "telecoin_mint_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): EventProjectedStakingRewardsRequest {
    return new EventProjectedStakingRewardsRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): EventProjectedStakingRewardsRequest {
    return new EventProjectedStakingRewardsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): EventProjectedStakingRewardsRequest {
    return new EventProjectedStakingRewardsRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a:
      | EventProjectedStakingRewardsRequest
      | PlainMessage<EventProjectedStakingRewardsRequest>
      | undefined,
    b:
      | EventProjectedStakingRewardsRequest
      | PlainMessage<EventProjectedStakingRewardsRequest>
      | undefined,
  ): boolean {
    return proto3.util.equals(EventProjectedStakingRewardsRequest, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.EventBuybackAndBurnRequest
 */
export class EventBuybackAndBurnRequest extends Message<EventBuybackAndBurnRequest> {
  /**
   * @generated from field: string telecoin_id = 1;
   */
  telecoinId = "";

  /**
   * @generated from field: printrfi.wingman.TokenAmount quote_spent = 2;
   */
  quoteSpent?: TokenAmount;

  /**
   * @generated from field: printrfi.wingman.TokenAmount telecoin_burned = 3;
   */
  telecoinBurned?: TokenAmount;

  /**
   * @generated from field: string transaction_id = 4;
   */
  transactionId = "";

  /**
   * @generated from field: string block_number = 5;
   */
  blockNumber = "";

  /**
   * @generated from field: optional google.protobuf.Timestamp block_timestamp = 6;
   */
  blockTimestamp?: Timestamp;

  constructor(data?: PartialMessage<EventBuybackAndBurnRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.EventBuybackAndBurnRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "telecoin_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "quote_spent", kind: "message", T: TokenAmount },
    { no: 3, name: "telecoin_burned", kind: "message", T: TokenAmount },
    { no: 4, name: "transaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "block_number", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "block_timestamp", kind: "message", T: Timestamp, opt: true },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): EventBuybackAndBurnRequest {
    return new EventBuybackAndBurnRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): EventBuybackAndBurnRequest {
    return new EventBuybackAndBurnRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): EventBuybackAndBurnRequest {
    return new EventBuybackAndBurnRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a: EventBuybackAndBurnRequest | PlainMessage<EventBuybackAndBurnRequest> | undefined,
    b: EventBuybackAndBurnRequest | PlainMessage<EventBuybackAndBurnRequest> | undefined,
  ): boolean {
    return proto3.util.equals(EventBuybackAndBurnRequest, a, b);
  }
}
