// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file wingman/wingman_inbound.proto (package printrfi.wingman, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { HealthResponse } from "./health_pb.js";
import { SolanaClaimFeesRequest, SolanaClaimFeesResponse } from "./solana_claim_fees_pb.js";
import {
  SolanaClaimStakingRewardsRequest,
  SolanaClaimStakingRewardsResponse,
} from "./solana_claim_staking_rewards_pb.js";
import { SolanaCreateCurveRequest, SolanaCreateCurveResponse } from "./solana_create_curve_pb.js";
import {
  SolanaCreateStakePositionRequest,
  SolanaCreateStakePositionResponse,
} from "./solana_create_stake_position_pb.js";
import {
  SolanaCurveProgressRequest,
  SolanaCurveProgressResponse,
} from "./solana_curve_progress_pb.js";
import {
  SolanaHasAssociatedTokenAccountRequest,
  SolanaHasAssociatedTokenAccountResponse,
} from "./solana_has_associated_token_account_pb.js";
import { SolanaLzBridgeRequest, SolanaLzBridgeResponse } from "./solana_lz_bridge_pb.js";
import {
  SolanaPrintFromEVMRequest,
  SolanaPrintFromEVMResponse,
  SolanaQuotePrintFromEVMResponse,
} from "./solana_print_from_evm_pb.js";
import { SolanaSwapRequest, SolanaSwapResponse } from "./solana_swap_pb.js";
import {
  SolanaXchainBuyOnSolanaRequest,
  SolanaXchainBuyOnSolanaResponse,
} from "./solana_xchain_buy_on_solana_pb.js";
import { XchainSpendOnEVMRequest, XchainSpendOnEVMResponse } from "./xchain_spend_on_evm_pb.js";

/**
 * @generated from service printrfi.wingman.WingmanInbound
 */
export const WingmanInbound = {
  typeName: "printrfi.wingman.WingmanInbound",
  methods: {
    /**
     * Use to check if the service is up and running and to determine latency.
     *
     * Read-only operation.
     *
     * @generated from rpc printrfi.wingman.WingmanInbound.Health
     */
    health: {
      name: "Health",
      I: Empty,
      O: HealthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the ixs to create a new curve on Solana.
     *
     * In the current version Solana telecoin can only be launched against the $wSOL token.
     *
     * Read-only operation.
     *
     * @generated from rpc printrfi.wingman.WingmanInbound.SolanaCreateCurve
     */
    solanaCreateCurve: {
      name: "SolanaCreateCurve",
      I: SolanaCreateCurveRequest,
      O: SolanaCreateCurveResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the ixs to either buy or sell telecoin.
     *
     * This will work regardless of whether we're on bonding curve or AMM.
     *
     * Read-only operation.
     *
     * @generated from rpc printrfi.wingman.WingmanInbound.SolanaSwap
     */
    solanaSwap: {
      name: "SolanaSwap",
      I: SolanaSwapRequest,
      O: SolanaSwapResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Same as SolanaSwap but estimates locally from fetched account state
     * instead of RPC transaction simulation.
     *
     * Read-only operation.
     *
     * @generated from rpc printrfi.wingman.WingmanInbound.SolanaSwapV2
     */
    solanaSwapV2: {
      name: "SolanaSwapV2",
      I: SolanaSwapRequest,
      O: SolanaSwapResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the ix to xchain swap from EVM to Solana and then buy telecoin with post hook.
     *
     * Read-only operation.
     *
     * @generated from rpc printrfi.wingman.WingmanInbound.SolanaXchainBuyOnSolana
     */
    solanaXchainBuyOnSolana: {
      name: "SolanaXchainBuyOnSolana",
      I: SolanaXchainBuyOnSolanaRequest,
      O: SolanaXchainBuyOnSolanaResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns calldata to bridge tokens from Solana to given destination chain via LayerZero.
     *
     * Read-only operation.
     *
     * @generated from rpc printrfi.wingman.WingmanInbound.SolanaLzBridge
     */
    solanaLzBridge: {
      name: "SolanaLzBridge",
      I: SolanaLzBridgeRequest,
      O: SolanaLzBridgeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Facilitates an intent of printing a telecoin on Solana from an EVM chain.
     *
     * @generated from rpc printrfi.wingman.WingmanInbound.SolanaPrintFromEVM
     */
    solanaPrintFromEVM: {
      name: "SolanaPrintFromEVM",
      I: SolanaPrintFromEVMRequest,
      O: SolanaPrintFromEVMResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Same as SolanaPrintFromEVM but without submittable tx.
     *
     * @generated from rpc printrfi.wingman.WingmanInbound.SolanaQuotePrintFromEVM
     */
    solanaQuotePrintFromEVM: {
      name: "SolanaQuotePrintFromEVM",
      I: SolanaPrintFromEVMRequest,
      O: SolanaQuotePrintFromEVMResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the progress on a Solana curve.
     *
     * Read-only operation.
     *
     * @generated from rpc printrfi.wingman.WingmanInbound.SolanaCurveProgress
     */
    solanaCurveProgress: {
      name: "SolanaCurveProgress",
      I: SolanaCurveProgressRequest,
      O: SolanaCurveProgressResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the ixs to claim fees from a curve.
     *
     * Read-only operation.
     *
     * @generated from rpc printrfi.wingman.WingmanInbound.SolanaClaimFees
     */
    solanaClaimFees: {
      name: "SolanaClaimFees",
      I: SolanaClaimFeesRequest,
      O: SolanaClaimFeesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns whether a user has an associated token account for a given Printr token.
     *
     * Read-only operation.
     *
     * @generated from rpc printrfi.wingman.WingmanInbound.SolanaHasAssociatedTokenAccount
     */
    solanaHasAssociatedTokenAccount: {
      name: "SolanaHasAssociatedTokenAccount",
      I: SolanaHasAssociatedTokenAccountRequest,
      O: SolanaHasAssociatedTokenAccountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the ixs to create a new staking position on Solana.
     *
     * Read-only operation.
     *
     * @generated from rpc printrfi.wingman.WingmanInbound.SolanaCreateStakePosition
     */
    solanaCreateStakePosition: {
      name: "SolanaCreateStakePosition",
      I: SolanaCreateStakePositionRequest,
      O: SolanaCreateStakePositionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the ixs to claim staking rewards on Solana.
     *
     * Read-only operation.
     *
     * @generated from rpc printrfi.wingman.WingmanInbound.SolanaClaimStakingRewards
     */
    solanaClaimStakingRewards: {
      name: "SolanaClaimStakingRewards",
      I: SolanaClaimStakingRewardsRequest,
      O: SolanaClaimStakingRewardsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Swap into any EVM chain from any Printr supported chain with posthook.
     *
     * Read-only operation.
     *
     * @generated from rpc printrfi.wingman.WingmanInbound.XchainSpendOnEVM
     */
    xchainSpendOnEVM: {
      name: "XchainSpendOnEVM",
      I: XchainSpendOnEVMRequest,
      O: XchainSpendOnEVMResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
