// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file wingman/xchain_spend_on_evm.proto (package printrfi.wingman, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Account } from "../caip/account_pb.js";
import { AssetAmount, EvmTx, PlatformPayload, XchainIntent } from "./misc_pb.js";

/**
 * @generated from message printrfi.wingman.XchainSpendOnEVMRequest
 */
export class XchainSpendOnEVMRequest extends Message<XchainSpendOnEVMRequest> {
  /**
   * The user that will sign the transaction.
   * Determines the source chain.
   *
   * Required.
   *
   * @generated from field: printrfi.caip.Account payer = 1;
   */
  payer?: Account;

  /**
   * User's recipient address on the destination EVM chain.
   * The chain id must match the one of the `evm_contract`.
   *
   * Required.
   *
   * @generated from field: printrfi.caip.Account recipient = 2;
   */
  recipient?: Account;

  /**
   * The amount to expect on the destination chain.
   * In another words, specifying this implies "exact output" swap on and the amount to spend
   * on the source will be determined by the provider.
   *
   * Only native is supported at the moment.
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.AssetAmount receive_on_destination = 3;
   */
  receiveOnDestination?: AssetAmount;

  /**
   * This will be added as-is as a post hook.
   *
   * <https://docs.relay.link/references/api/get-quote#body-txs>
   *
   * @generated from field: printrfi.wingman.EvmTx posthook = 4;
   */
  posthook?: EvmTx;

  /**
   * Slippage in basis points (1/100 of a percent).
   *
   * @generated from field: optional uint32 slippage_bps = 5;
   */
  slippageBps?: number;

  /**
   * Who should receive the refund in case the transaction reverts.
   * Must be an account on the same chain as the `payer`.
   *
   * Required.
   *
   * @generated from field: printrfi.caip.Account send_refund_to = 6;
   */
  sendRefundTo?: Account;

  /**
   * The token to spend on the source chain.
   *
   * Optional.
   * If not provided, native token of the source chain will be used.
   *
   * @generated from field: printrfi.caip.Account spend_token = 7;
   */
  spendToken?: Account;

  constructor(data?: PartialMessage<XchainSpendOnEVMRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.XchainSpendOnEVMRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "payer", kind: "message", T: Account },
    { no: 2, name: "recipient", kind: "message", T: Account },
    { no: 3, name: "receive_on_destination", kind: "message", T: AssetAmount },
    { no: 4, name: "posthook", kind: "message", T: EvmTx },
    { no: 5, name: "slippage_bps", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 6, name: "send_refund_to", kind: "message", T: Account },
    { no: 7, name: "spend_token", kind: "message", T: Account },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): XchainSpendOnEVMRequest {
    return new XchainSpendOnEVMRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): XchainSpendOnEVMRequest {
    return new XchainSpendOnEVMRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): XchainSpendOnEVMRequest {
    return new XchainSpendOnEVMRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a: XchainSpendOnEVMRequest | PlainMessage<XchainSpendOnEVMRequest> | undefined,
    b: XchainSpendOnEVMRequest | PlainMessage<XchainSpendOnEVMRequest> | undefined,
  ): boolean {
    return proto3.util.equals(XchainSpendOnEVMRequest, a, b);
  }
}

/**
 * @generated from message printrfi.wingman.XchainSpendOnEVMResponse
 */
export class XchainSpendOnEVMResponse extends Message<XchainSpendOnEVMResponse> {
  /**
   * Required.
   *
   * @generated from field: printrfi.wingman.XchainIntent intent = 1;
   */
  intent?: XchainIntent;

  /**
   * How much will the user spend on the tx.
   * Native asset of the source chain.
   *
   * @generated from field: printrfi.wingman.AssetAmount source_gas_cost = 2;
   */
  sourceGasCost?: AssetAmount;

  /**
   * How much will the user spend on xchain fee.
   * Might not be the same asset as gas cost but will be the same chain.
   *
   * @generated from field: printrfi.wingman.AssetAmount xchain_fee_cost = 3;
   */
  xchainFeeCost?: AssetAmount;

  /**
   * Required.
   *
   * @generated from field: printrfi.wingman.AssetAmount spend_on_source = 4;
   */
  spendOnSource?: AssetAmount;

  /**
   * Execute this payload on the source chain.
   *
   * Required.
   *
   * @generated from field: printrfi.wingman.PlatformPayload payload = 5;
   */
  payload?: PlatformPayload;

  constructor(data?: PartialMessage<XchainSpendOnEVMResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "printrfi.wingman.XchainSpendOnEVMResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "intent", kind: "message", T: XchainIntent },
    { no: 2, name: "source_gas_cost", kind: "message", T: AssetAmount },
    { no: 3, name: "xchain_fee_cost", kind: "message", T: AssetAmount },
    { no: 4, name: "spend_on_source", kind: "message", T: AssetAmount },
    { no: 5, name: "payload", kind: "message", T: PlatformPayload },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): XchainSpendOnEVMResponse {
    return new XchainSpendOnEVMResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): XchainSpendOnEVMResponse {
    return new XchainSpendOnEVMResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): XchainSpendOnEVMResponse {
    return new XchainSpendOnEVMResponse().fromJsonString(jsonString, options);
  }

  static equals(
    a: XchainSpendOnEVMResponse | PlainMessage<XchainSpendOnEVMResponse> | undefined,
    b: XchainSpendOnEVMResponse | PlainMessage<XchainSpendOnEVMResponse> | undefined,
  ): boolean {
    return proto3.util.equals(XchainSpendOnEVMResponse, a, b);
  }
}
