import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerRemoteSafeTools } from "@printr/mcp/remote-safe";
import { createPrintrClient } from "@printr/sdk";
import { McpAgent } from "agents/mcp";

import { sessionRoutes } from "./session-routes.js";
import { registerRemoteWebSignerTool } from "./web-signer-tool.js";

// `Env` is generated by `wrangler types` from wrangler.jsonc — do not hand-write.

export { SigningSessionDO } from "./signing-session.js";

/**
 * Remote Printr MCP server hosted on Cloudflare Workers. Exposes the
 * read + build-unsigned tool surface (via {@link registerRemoteSafeTools}) plus
 * the browser web-signer (a Durable-Object-backed signing session); raw
 * private-key signing and keystore tools stay local-only.
 */
export class PrintrMCP extends McpAgent<Env> {
  server = new McpServer({ name: "printr", version: "0.1.0" });

  async init(): Promise<void> {
    // Public preview API is keyless; pass a base URL only.
    const client = createPrintrClient({ baseUrl: this.env.PRINTR_API_BASE_URL });

    registerRemoteSafeTools(this.server, client);
    registerRemoteWebSignerTool(this.server, {
      sessions: this.env.SIGNING_SESSION,
      appUrl: this.env.PRINTR_APP_URL,
      publicOrigin: this.env.PUBLIC_ORIGIN,
    });
  }
}

export default {
  fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> | Response {
    const url = new URL(request.url);

    // Web-signer session API (talks to the Printr web app's /sign page).
    if (url.pathname === "/health" || url.pathname.startsWith("/sessions")) {
      return sessionRoutes().fetch(request, env, ctx);
    }

    // Streamable HTTP transport (current MCP spec).
    if (url.pathname === "/mcp") {
      return PrintrMCP.serve("/mcp").fetch(request, env, ctx);
    }

    // SSE transport (legacy clients).
    if (url.pathname === "/sse" || url.pathname === "/sse/message") {
      return PrintrMCP.serveSSE("/sse").fetch(request, env, ctx);
    }

    return new Response("Not found", { status: 404 });
  },
} satisfies ExportedHandler<Env>;
